### ISSUE TITLE
Error: Cannot find module 'worker!./[workername]'

### ISSUE THREAD

**Issue by benwiley4000** [webpack-contrib/worker-loader#10]
So I'm having some issues that are difficult to debug. I'm creating an npm module library to be used in a separate project that includes that module. So I've been building the module - it creates a bundle.js and a separate worker file with it in the build directory - then I run the project, and I don't get any errors, but it doesn't seem like the Worker is actually doing anything/receiving my messages. Maybe it's not actually finding the file because it's in a separate module/not linked correctly?

So I tried to test this in the project itself by putting the Worker source file in the same directory as my index.js, building, and running. But when I run it, I get this error:

`Error: Cannot find module 'worker!./[workername]'`

For reference, This is excerpted from my code (I'm using React):

```
var [workername] = require('worker!./[workername]');

...

class ComponentName extends React.Component {
  ...
  componentDidMount () {
    var worker = new [workername]();
    function logMessage (e) {
      console.log(e.data);
    }
    worker.onmessage = logMessage;
    console.log('worker made',worker);
    setInterval(function () {
      worker.postMessage('start');
    }, 1000);
  }
}
```

and this is my worker (but not sure if that matters since it doesn't even recognize the module!):

```
self.onmessage = function (e) {
    postMessage('message received!');
};
```

Help?

**Comment by benwiley4000** [comment]
By the way, this is a successful workaround that takes advantage inline workers (http://www.html5rocks.com/en/tutorials/workers/basics/#toc-inlineworkers), together with webpack's raw-loader (https://github.com/webpack/raw-loader), to allow the worker to exist in a separate file but then be packed in with the bundle.js.

```
var workerScript = require('raw!./worker.js');

... (after loading / window object is available) ...

var worker = new Worker(window.URL.createObjectURL(new Blob([
  workerScript
])));
```

**Comment by nakedsushi** [comment]
I'm having this exact problem.

```
// main.ts
import Worker = require("worker!./blah.worker.js");
```

The `blah.worker.js` file is in the same directory as main.ts, but I still get:

```
 Cannot find module 'worker!./blah.worker.js'.
```

**Comment by JuHwon** [comment]
I am having this issue in my jest test runner :/
what can i do to solve this?

**Comment by TrySound** [comment]
@JuHwon Jest uses node. Node doesn't know about `worker!` because it's webpack stuff. It means you didn't bundle something.

**Comment by phaattran** [comment]
@JuHwon Yeah like @TrySound said, you need to map all worker files to some mock in your moduleMapper in package.json like so:
```js
{
"jest": {
    "moduleNameMapper": {
      "\\.worker.js":"<rootDir>/__mocks__/workerMock.js"
    }
  }
}
```
Obviously you should have a `__mock__` folder with `workerMock.js` in it, it could be something like this:
```js
module.exports = Object.create(null);
```
This is more like a jest issue rather than a webpack issue.

**Comment by peteringram0** [comment]
Has anyone got a good solution for this?

**Comment by nschwan94** [comment]
I'm sure there's a few different workarounds here depending on the exact usage of the worker-loader import.

I unit test my method that instantiated a worker thread with these lines:
```
    var FilterThread = require('worker-loader?inline!./FilterThread.js')
    const filterThread = new FilterThread()
```

I simply moved them into a utility method `getWorkerThread` and then mocked that utility method with `jest.fn()` returning a mocked `constructor`, `postMessage`, and `addEventListener` method.

```
getWorkerThread =
      jest.fn(() => {
        return {
          constructor: jest.fn(),
          postMessage: jest.fn(),
          addEventListener: jest.fn((mes, e, bool) => {
            e()
          }),
        }
      })
```

Now my test code never calls the problematic `require('worker-loader?inline!./FilterThread.js')` but still achieves mocked functionality. This example doesn't seem to apply directly to OP, but may be of use to those who navigate here... since there's minimal conversation on topic.

**Comment by Kuzirashi** [comment]
I'd like to emphasize that @phaattran solution works. Check it out.
