### ISSUE TITLE
[Question] Why this package is so hard to use

### ISSUE THREAD

**Issue by fsx950223** [webpack-contrib/worker-loader#101]
When I use the loader, I get a lot of problems and there is nothing to say about them and no test. How can I use it like `window.Worker`

**Comment by michael-ciniawsky** [comment]
Post the file where you `import` the `Worker` && your `webpack.config.js` please

**Comment by fsx950223** [comment]
```
{
        test: /\.worker\.js$/,
        loader: 'worker-loader'
      },
```
I need to install loader-utils by myself
```
import uploadWorker from '../upload.worker.js'
const worker=new uploadWorker()
```
result: worker undefined

**Comment by michael-ciniawsky** [comment]
```js
{
   test: /\.worker\.js$/,
   use: {
     loader: 'worker-loader',
     options: { inline: true }
   }
}
```

Please ensure to have a clean install by `npm cache clean [--force*] && rm -rf node_modules`

> \* `npm >= v5.0.0`
