### ISSUE TITLE
Release v0.8.2 with updated peerDependency on webpack@^3.0.0

### ISSUE THREAD

**Issue by elliottsj** [webpack-contrib/worker-loader#103]
I'm currently stuck on worker-loader@^0.8.0 due a combination of issues related to pdfjs-dist and npm shrinkwrap: https://github.com/mozilla/pdf.js/issues/9059

Would it be possible to release worker-loader@0.8.2 with just [this change](https://github.com/webpack-contrib/worker-loader/commit/f7e213233eba3ca6310bd6d46f7985858cbb3b99)?

I realize this would _technically_ be a breaking change since someone using worker-loader@^0.8.0 _and_ webpack@2.1.0-beta would no longer satisfy the constraint `>=0.9 || ^2.0.0 || ^3.0.0`, but I think this is a small edge case, and those users (if they exist) can pin their worker-loader version to 0.8.1 to avoid any issues.

**Comment by michael-ciniawsky** [comment]
Nope sry, this was a breaking change and is 'correct' from our side
