### ISSUE TITLE
Source maps not working for error traces

### ISSUE THREAD

**Issue by samuelcolvin** [webpack-contrib/worker-loader#108]
Hi, I'm getting proper traces with non worker code. But with `*.worker.js` code I get raw trace on errors which are hard to read.

Is there someway to get worker-loader to play nicely with source-maps/devtools?

dependencies:
```
  "dependencies": {
    "babel-eslint": "^7.2.3",
    "date-fns": "^1.29.0",
    "dexie": "^2.0.1",
    "eslint": "^4.1.1",
    "eslint-config-react-app": "^2.0.1",
    "eslint-plugin-flowtype": "^2.34.1",
    "eslint-plugin-import": "^2.6.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.1.0",
    "lodash": "^4.17.4",
    "react": "^16.0.0",
    "react-app-rewired": "^1.3.3",
    "react-bootstrap-typeahead": "^2.0.0-alpha.6",
    "react-dom": "^16.0.0",
    "react-router-dom": "^4.2.2",
    "react-scripts": "1.0.14",
    "webpack": "3.0.0",
    "worker-loader": "^1.1.0"
  },
```

I'm using worker-load with non-ejected `create-react-app`, using [this](https://github.com/facebookincubator/create-react-app/issues/1277#issuecomment-313950613) code.

Example of trace from chromium:

![image](https://user-images.githubusercontent.com/4039449/32910097-409c6950-cb00-11e7-884c-380b4c8791bc.png)

I hope that's enough information. If there's anything else you need let me know

**update:**

Forgot to say: all the links in the above trace are to the current url, not a js file.

If I disable the babel loader for `*.worker.js` files the trace works fine.

I've tried `inline: true` and `inline: flase` but to no avail.

**Comment by richdyang** [comment]
+1

**Comment by mikehardenize** [comment]
I am also experiencing this issue

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack-contrib/worker-loader/issues/245
