### ISSUE TITLE
[Feature] support `ServiceWorker`

### ISSUE THREAD

**Issue by opatut** [webpack-contrib/worker-loader#11]
Yes, I know, they are different things. **But**...
- ... [serviceworker-loader](https://github.com/markdalgleish/serviceworker-loader), is dead
- ... and it is basically a copy of an old version of this, with minor adjustments
- ... because most of the webpack code is the same for a service worker (emit a new file, allow instanciation), only the instanciation helper is different
- ... and they don't share the "worker" part of their name for no reason :)

**Comment by michael-ciniawsky** [comment]
#32

**Comment by sizeak** [comment]
Is this in master yet?

**Comment by webxl** [comment]
@sizeak Try this: https://github.com/mohsen1/service-worker-loader#readme

**Comment by sizeak** [comment]
Thanks, will take a look. I'm currently using this https://www.npmjs.com/package/cra-append-sw

**Comment by evilebottnawi** [comment]
Fixed https://github.com/webpack-contrib/worker-loader/pull/247

**Comment by pigcan** [comment]
@ekulabuhov Could you release a new version?

**Comment by evilebottnawi** [comment]
@pigcan This week

**Comment by pigcan** [comment]
Great! Thank you!

Evilebot Tnawi <notifications@github.com> 于2020年7月29日周三 下午8:11写道：
