### ISSUE TITLE
Not work in typescript 2.4

### ISSUE THREAD

**Issue by itfinally** [webpack-contrib/worker-loader#111]
Hello , in typescript 2.4, worker-loader 1.1.0, it not work.

I following the chapter of "Integrating with TypeScript" to write this file:
```
// web_worker.d.ts

declare module "worker-loader!*" {
    class WebpackWorker extends Worker {
        constructor();
    }

    export = WebpackWorker;
}
```

```
// bootstrap.ts

import Worker from "worker-loader!./src/test.worker";

let worker = new Worker();
```

Oh, also i have the configuration in the tsconfig.json
```
"files": [
    "src/web_worker.d.ts"
  ]
```

But got this exception -> `TS1192: Module '"worker-loader!*"' has no default export.` 
So how can i running this?

**Comment by pconerly** [comment]
You need `export default WebpackWorker;` not `export = WebpackWorker;`

**Comment by michael-ciniawsky** [comment]
@itfinally See @pconerly comment @pconerly Thx 👍 Feel free to reopen if still regressions :)
