### ISSUE TITLE
Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': An object could not be cloned

### ISSUE THREAD

**Issue by vikasraj789** [webpack-contrib/worker-loader#114]
Package version: 1.1.0
This error comes up when I try to send new Objects from worker to Main thread.

**Comment by evilebottnawi** [comment]
@vikasraj789 Thank for issue. See https://stackoverflow.com/questions/42376464/uncaught-domexception-failed-to-execute-postmessage-on-window-an-object-co.
