### ISSUE TITLE
Filename ?

### ISSUE THREAD

**Issue by peteringram0** [webpack-contrib/worker-loader#118]
Can you only specify a single output file name within the webpack.config? I load multiple workers and would like the ability to keep individual names on output. 

Thanks.

**Comment by jwmann** [comment]
You can do this through the import declaration.
Though doing this may make you run into the same issue I had where if you're using the rule method to 'look' for your workers, it'll generate 2 files for each worker. 

Here's an example of what you need, but check out my issue in #117 for more info.

````
import rowsExportWorker from 'worker-loader?name=/dist/rows.export.worker.js&inline=true!../workers/rows.export.worker';
import columnsExportWorker from 'worker-loader?name=/dist/columns.export.worker.js&inline=true!../workers/columns.export.worker';
import pdfExportWorker from 'worker-loader?name=/dist/pdf.export.worker.js&inline=true!../workers/pdf.export.worker';
import csvExportWorker from 'worker-loader?name=/dist/csv.export.worker.js&inline=true!../workers/csv.export.worker';
import excelExportWorker from 'worker-loader?name=/dist/excel.export.worker.js&inline=true!../workers/excel.export.worker';
````

**Comment by peteringram0** [comment]
Thanks that fixed my issue. No duplicate files being generated also :)
