### ISSUE TITLE
Emitted files cannot be included in manifests

### ISSUE THREAD

**Issue by jgable** [webpack-contrib/worker-loader#119]
Repro Repo: https://github.com/jgable/worker-loader-manifest-example

Repro steps:

- `git clone git@github.com:jgable/worker-loader-manifest-example.git && cd worker-loader-manifest-example`
- `npm install && npm run example && cat public/javascripts/webpack-manifest.json`
   - There are a bunch of unnecessary dependencies but I wanted it to match our production environment as much as possible

We use the [ManifestPlugin](https://github.com/danethurber/webpack-manifest-plugin) to upload our built assets to a CDN after the build. With this loader we are building a file but it does not show up in any manifest for us to be aware of and upload.

At first I thought this was because this plugin creates and runs its own child compiler without our plugins but as a test I hard coded in support for plugins (and passed our manifest plugins in) being passed to the child compiler and still couldn't get the built worker files in my manifest.

As an aside question, why does this plugin use a child compiler approach? It seems we have to repeat things like plugins and output.publicPath because of this approach.

**Comment by evilebottnawi** [comment]
You need to open an issue in https://github.com/danethurber/webpack-manifest-plugin repo, the plugin should respect assets from child compilations, we can't fix it on our side, sorry for delay
