### ISSUE TITLE
IE11 ES6 shim?

### ISSUE THREAD

**Issue by jwmann** [webpack-contrib/worker-loader#120]
My Web Workers work beautifully on every browser except for IE10-11
It's getting upset that I'm using ES6.
I'm trying to include an ES6 shim in my web worker like so:

````
require('es6-shim');

onmessage = function( event ) {
  console.log( 'rowsWorker', 'Start', event.data );
  const { foo, bar } = event.data;
  postMessage( "Please IE." );
}
````

But it seems to be ignored or something because it doesn't work. I tried `babel-polyfill` as well but no dice. Am I missing something?

**Comment by evilebottnawi** [comment]
@jwmann worker have own context, you should `require` inside worker context - i.e. look https://github.com/webpack-contrib/worker-loader#config inside `file.worker.js`

**Comment by jwmann** [comment]
@evilebottnawi That's exactly where this code is from. My worker.

**Comment by evilebottnawi** [comment]
@jwmann hm, should be work, can you create minimum reproducible test repo?

**Comment by jwmann** [comment]
I managed to solve this in a different way.
I don't need the `es6-shim` at all if I pass it through `babel-loader` in my `import`

````
import rowsExportWorker from 'worker-loader?name=/dist/rows.export.worker.js&publicPath=/modules/custom/mt360/app!babel-loader!../workers/rows.export.worker';
````

Adding `!babel-loader` fixed it.
