### ISSUE TITLE
Every worker receives every message

### ISSUE THREAD

**Issue by mikehardenize** [webpack-contrib/worker-loader#127]
Given the following code, both message handlers in the workers receive both postMessages... This seems wrong to me?

```js
import Worker1 from './file1.worker.js';
import Worker2 from './file2.worker.js';

const worker1 = new Worker1();
const worker2 = new Worker2();

worker1.postMessage({ a: 1 });
worker2.postMessage({ a: 2 });
```

I could pass a "worker id" along with the postMessage, and then in the message handler, I could check to make sure that the worker id matches and ignore if not, but I feel like this should be abstracted away.

**Comment by evilebottnawi** [comment]
Can't reproduce the problem on the master branch, looks like it was fixed.

**Comment by crutch12** [comment]
Hi @alexander-akait 
I've got the same problem after update to worker-loader@3.0.6 (previous @2.0.0 worked fine)
