### ISSUE TITLE
lodash is in the worker bundle and vendor

### ISSUE THREAD

**Issue by wizardnet972** [webpack-contrib/worker-loader#132]
When I import lodash into the worker file, it is exist in the worker bundle and vendor bundle.

It is need to exist only in vendor.

some.worker.js:
```
const _ = require('lodash');
const a = _.map([1,2,3], s => s);
```

webpack.config.js:
```
entry: {
    vendor: ["jquery", "lodash"],
    main: './app/index.js',
 },
modules/rules:
{
 test: /\.worker\.js$/,
 use: { loader: 'worker-loader' },
},
```

**Comment by gabberr** [comment]
Web workers global scope is different from the window global scope.

When your 'vendor.js' is loaded, it adds lodash  to to window object. Web worker does not have access to it.

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack-contrib/worker-loader/issues/70
