### ISSUE TITLE
[Question] Multiple requests & number of threads

### ISSUE THREAD

**Issue by melloc01** [webpack-contrib/worker-loader#141]
Hello,

I am using `worker-loader` to make some calculations on large amount of data  that comes from my back-end per `chart` on a dashboard. This means I am actually making:
```js
this.myworker =  new Worker()
```
on every chart of the dashboard. Some dashboards may contain 50~ish charts, which brings me here:

1. Those 50 charts instantiating `Worker` would cause **50 network hits**? btw.: I am using service workers.
2. Is there any harm to have 50+ threads running on a tab? 

ps.: I tried to find those answers in the wild but didn't find anyone being straight to the point

**Comment by gpolyn** [comment]
@melloc01 I've read about a distinction between "physical" threads and "software" threads, such that creating many web workers may result in more software threads than available physical threads. 

So, a developer may wish to mind the user's hardware utilization and create fewer or no more than the available number of physical threads, e.g., https://github.com/josdejong/workerpool/blob/master/lib/Pool.js.

I wanted to play with this idea (for React) and you can find my attempt at `worker-loader` pooling here: https://github.com/gpolyn/react-and-worker-loader/blob/master/src/workerPool2.js

**Comment by evilebottnawi** [comment]
Please ask questions on stackoverflow, it is bug tracker
