### ISSUE TITLE
Window is not defined - when using hotModuleReplacementPlugin

### ISSUE THREAD

**Issue by melloc01** [webpack-contrib/worker-loader#142]
In the [docs](https://webpack.js.org/plugins/hot-module-replacement-plugin/) there's not regexp to ignore modules with filename patterns like `/\.worker\.js$/`, this could be a solution.

Compilation output, in the 2nd line of the output window is being accessed:

```js
/******/ (function(modules) { // webpackBootstrap
/******/ 	var parentHotUpdateCallback = window["webpackHotUpdate"];
/******/ 	window["webpackHotUpdate"] = // eslint-disable-next-line no-unused-vars
/******/ 	function webpackHotUpdateCallback(chunkId, moreModules) {
/******/ 		hotAddUpdateChunk(chunkId, moreModules);
/******/ 		if (parentHotUpdateCallback) parentHotUpdateCallback(chunkId, moreModules);
/******/ 	} ;
/******/
/******/ 	// eslint-disable-next-line no-unused-vars
/******/ 	function hotDownloadUpdateChunk(chunkId) {
/******/ 		importScripts(__webpack_require__.p + "" + chunkId + "." + hotCurrentHash + ".hot-update.js");
/******/ 	}
/******/
...
```

**Comment by lilbumblebear** [comment]
I also ran into this issue, I used the following workaround in webpack.config.js,  **globalObject: 'this'**

example: 

    output: {
       path: path.join(__dirname, 'dist'),
       filename: 'bundle.js'
       publicPath: 'http://localhost:3000',
       globalObject: 'this'
      },


Source https://github.com/webpack/webpack/issues/6642

**Comment by melloc01** [comment]
Cool, thanks @lilbumblebear
