### ISSUE TITLE
worker-loader seems to inject web assembly binary contents directly into JavaScript output bundle

### ISSUE THREAD

**Issue by itsybitesyspider** [webpack-contrib/worker-loader#144]
[wasm-loader-problem.tar.gz](https://github.com/webpack-contrib/worker-loader/files/1976088/wasm-loader-problem.tar.gz)

Attached an example project. You can run it using npm install followed by npm build or npm start. The web assembly is pre-built for you, but if you want to build it yourself using a rust toolchain, you can do so using the included Makefile.

I can load and execute a simple web assembly function (add two numbers and return the result) using webpack, which works (commented out in the example project). However, if I do the same thing in a web worker created using worker-loader, the web worker experiences a syntax error.

On further examination of the worker's JavaScript output bundle, I find something like this:

```
/***/ "./rust-wasm-package/pkg/rust_wasm_package_bg.wasm":
/*!*********************************************************!*\
  !*** ./rust-wasm-package/pkg/rust_wasm_package_bg.wasm ***!
  \*********************************************************/
/*! exports provided: memory, add, __wbindgen_malloc */
/***/ (function(module, exports, __webpack_require__) {

eval("\u0000asm\u0001\u0000\u0000\u0000\u0001}\u0012`\u0001...
```

Which I assume is not correct.

I'm not sure what to make of this. It seems that WebPack, once invoked within the worker-loader, can't recognize wasm resources or doesn't care and treats it as JavaScript.

**Comment by cars10** [comment]
+1, same problem

**Comment by clanehin** [comment]
@cars10 I dealt with it by using a separate entry point for the for the web-worker. Webpack can load wasm correctly, just not via worker-loader.

**Comment by dakom** [comment]
@clanehin - do you mind sharing how you've done multiple entry points for workers, in webpack4 ?

I've posted a similar question to Stackoverflow here: https://stackoverflow.com/questions/52437858/multiple-targets-per-entry-in-webpack-4

**Comment by cars10** [comment]
@dakom after playing around with the issue i created an example repo showing how to use wasm + workers + webpack together, maybe that will help you.
https://github.com/cars10/rust-wasm-webworker-example

**Comment by dakom** [comment]
thanks! though I see you're loading the wasm directly... I believe wasm-bindgen requires using its own generated js?

**Comment by cars10** [comment]
I am not sure TBH - though the example in this project works if you try it out.

**Comment by xtuc** [comment]
Why is the binary inject into the ouput JS? Our implementation of WebAssembly in Webpack uses `WebAssembly.instantiateStreaming`, I guess we could have the same support here?

**Comment by cars10** [comment]
Is it though? I also use `instantiateStreaming`, see https://github.com/cars10/rust-wasm-webworker-example/blob/master/src/js/worker.js#L3 .

**Comment by clanehin** [comment]
@dakom, I'm using webpack 4 with wasm-bindgen, and it goes just fine day-to-day even though it was time consuming to figure out the first time due to poor error messages. You can provide an array of configurations. However, a critical insight for me was that the different configurations in the array can stomp on each other's output, and this will result in extremely difficult-to-diagnose errors. You must provide an `output: { filename: "[name].unique-pattern.js" }` as part of each entry point to ensure that this does not happen.

Webpack could make this a lot easier by checksumming or UUID-ing module loads so you get immediate feedback if you unexpectedly load a weird module.

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack-contrib/worker-loader/issues/251
