### ISSUE TITLE
"Deprication warning: Tapable.apply is deprecated. Call apply on the plugin directly instead" is shown when running webpack's tests

### ISSUE THREAD

**Issue by tryzniak** [webpack-contrib/worker-loader#148]
Hello. I think I spotted something odd. I noticed that when running webpack's there's a deprecation warning log out which should have probably been fixed in 04bc4ffc5fd537072718eb9401107b32c9418b6b. 

Node version: 8.9.4
webpack version: HEAD/master, commit 360503587ecb1
worker-loader version: ^1.1.1

**Comment by shellscape** [comment]
Please don't ignore or remove issue templates. It's poor form. This was already fixed and is awaiting publish.
