### ISSUE TITLE
How to use it with Create React App

### ISSUE THREAD

**Issue by subhranshudas** [webpack-contrib/worker-loader#149]
Question - How to use worker loader with Create React App? Tried ejecting the CRA and putting webpack loader but i get something like -

```
./src/App.js
17:17-23 "export 'default' (imported as 'Worker') was not found in './worker.js'
```

version- "worker-loader": "^1.1.1"

**Comment by evilebottnawi** [comment]
@subhranshudas please create this question inside `Create React App` repo. Thanks!

**Comment by subhranshudas** [comment]
@evilebottnawi thanks for the reply.

Have also created there one - https://github.com/facebook/create-react-app/issues/4505

They have it in their backlog - https://github.com/facebook/create-react-app/pull/3934
But thats for non-ejected setup which comes out of the box which is yet to be merged.

I am also trying for a ejected set up as well. 
Typically `worker-loader` works for me in a normal webpack bundled project.

But want to know from `worker-loader` team, is there any standard procedure to integrate with CRA.

**Comment by evilebottnawi** [comment]
@subhranshudas no, we don't have standard procedure to integrate with CRA. A lot of boilerplates and CLIs build on webpack, we can't documented this in own README, it is should be done inside boilerplate docs.

**Comment by subhranshudas** [comment]
@evilebottnawi thanks for the reply, btw if you would be interested to know, the following is what i tried with 
https://github.com/facebook/create-react-app/issues/4505#issuecomment-391409030

**Comment by GaryBer** [comment]
You have to use :

const myWorker = require('./myWorker.js'); // if using ts-loader and not ES6 imports
