### ISSUE TITLE
Failed to construct 'Worker': Script at ... cannot be accessed from origin ...

### ISSUE THREAD

**Issue by romanlex** [webpack-contrib/worker-loader#154]
Hello, my web-worker doesn't load in production when use different servers for app and assets
`
16.8e953915c614.js:1 Uncaught DOMException: Failed to construct 'Worker': Script at 'https://assets.domain.ru/assets/43ec99c0a496c8cc2afe.worker.js' cannot be accessed from origin 'https://domain.ru'.
`

I'm import worker in my webpack chunk and use worker-loader
```import Worker from './generator.worker'```

How I can correct load worker inside chunk?

**Comment by evilebottnawi** [comment]
@romanlex Using https://developer.mozilla.org/ru/docs/Web/HTTP/CORS

**Comment by romanlex** [comment]
@evilebottnawi you mean what I need add cors headers on my assets servers?

**Comment by evilebottnawi** [comment]
@romanlex yep

**Comment by romanlex** [comment]
CORS is enabled on assets servers but it is doesn't help
May be I can use dynamic import and load with function
```
const asynsLoadWorker = () => import('./GeneratorWorker').then(module => module).catch(error => console.error(error))
```
But with this I need get blob of file

**Comment by uc2pac** [comment]
@romanlex , I have the same issue. I can't switch to inline worker since inline worker is not working in IE. Did you found any other solution?

**Comment by evilebottnawi** [comment]
You need to setup CORS `https://domain.ru`, adding `Access-Control-Allow-Origin` header, here more information https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by lwyj123** [comment]
Cant' load cross origin script too. even add `CORS` headers

**Comment by fiftin** [comment]
Same issue. I have all required CORS headers but got this error.

**Comment by aocenas** [comment]
I guess the issue mentioned here is the ultimate reason for this and why cors don't work as expected: https://stackoverflow.com/questions/25458104/can-should-html5-web-workers-use-cors-for-cross-origin
