### ISSUE TITLE
Dynamic name for output file

### ISSUE THREAD

**Issue by otakustay** [webpack-contrib/worker-loader#156]
Currently `worker-loader` supports a `name` option to specify the name of worker file, however in many projects only a single `worker-loader` serves all worker files, such like:

```js
{
  test: /\.worker\.js/,
  use: [
    {
      loader: 'worker-loader',
      options: {
        name: 'how can this be?'
      }
    }
  ]
```

If the `name` options can be a function receiving some compilation context, the name of output file can be beautified:

```js
{
  test: /\.worker\.js/,
  use: [
    {
      loader: 'worker-loader',
      options: {
        name: ({resource}) => basename(resource, extname(resource)) + '.[hash].js'
      }
    }
  ]
```

Is it even possible to have this feature?

**Comment by gabberr** [comment]
How about the [name] token ? It is not documented but it works.  
`{
 name: 'workers/[name].[hash].js'
}'
`

**Comment by otakustay** [comment]
Yes, `[name]` token solves the issue, thanks
