### ISSUE TITLE
Inline option doesn't work with IE11

### ISSUE THREAD

**Issue by bububo** [webpack-contrib/worker-loader#157]
Hello.
Using `inline: true` I've got a syntax error:
_Failed to open blob:F346C061-E14F-49A6-9C95-6AF09AF95357_

As I understood after quick googling IE11 doesn't support regular blob and has own API for opening blob.

Thanks

**Comment by gabberr** [comment]
As i understand, the up-to-date IE 11 supports it.
https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/11673552-support-web-worker-creation-via-blob-urls

Try to run it without the inline option, maybe you get some other more descriptive error.

**Comment by evilebottnawi** [comment]
Update browser to latest version, if you still have a problem(s), feel free to open a new issue with reproducible test repo
