### ISSUE TITLE
Issue when trying to cache xxx.worker.js files

### ISSUE THREAD

**Issue by adamzerner** [webpack-contrib/worker-loader#160]
worker-loader version: 1.1.1
Node version: 8.9.1
OS: Mac OSX

I've been having an issue with https://stackoverflow.com/questions/52265855/service-worker-wont-install-when-i-try-to-cache-xxx-worker-js for a while. I'm not sure if the issue is with `worker-loader` or not, but in looking through the issues and pull requests here, I got the impression that `worker-loader` can behave weirdly when trying to cache `xxx.worker.js` files, especially from https://github.com/webpack-contrib/worker-loader/pull/93, which was declined.

I tried to reproduce the issue [here](https://github.com/adamzerner/demo-of-worker-loader-caching-issue), but to my surprise, I was unable to. If this doesn't meet the requirements for support I totally understand, but if you were able to help me I would greatly, greatly appreciate it.

**Comment by evilebottnawi** [comment]
Fixed in the master, ETA is current week
