### ISSUE TITLE
Allow to use function as publicPath

### ISSUE THREAD

**Issue by nkbt** [webpack-contrib/worker-loader#161]
Webpack has added support to use use function as `publicPath` quite a while ago, it would probably be good to match this functionality

Commit: https://github.com/webpack/webpack/commit/fb4070442a3c0feb115dbb9229ccd0dc1458b30d

**Comment by pardoman** [comment]
Agreed. 

I'll try to send a PR for this since it's trivial to implement.
We just need to update this section: https://github.com/webpack-contrib/worker-loader/blob/5718fc1729fb1e2fc1a359637929fab7fc3a3b41/src/workers/index.js#L5-L7

**Comment by evilebottnawi** [comment]
It was implemented, but incorrect, so now we have https://github.com/webpack-contrib/worker-loader/issues/199 (close in favor)
