### ISSUE TITLE
Unable to name worker threads

### ISSUE THREAD

**Issue by Pan-Bubr** [webpack-contrib/worker-loader#162]
As far as I know `worker-loader` do not provide reasonable way to create name for the Worker Thread for debugging purposes. Now all workers are named with hashed numbers (i.e. `#23`), while in the ES6 spec you can pass optional parameters with `[WORKER_NAME]` like this:

`let worker = new Worker('path/to/my.worker.js', { name: '[WORKER_NAME]' });`

I see no implementation in `worker-loader`. Passing arguments to the constructor do not work and I see no alternative.

It'd be nice to have it working like this:
`let worker = new MyImportedWorker({ name: '[WORKER_NAME]' });`

If the option already exists, then it'd be nice to have it in the README.md

**Comment by lamuertepeluda** [comment]
Hi there, 

I'd also find this useful.
It should be possible to pass the worker constructor options [described here](https://developer.mozilla.org/en-US/docs/Web/API/Worker/Worker) when importing my worker, e.g.:

```js
import Worker from './file.worker.js';
const options = { name: 'my-worker'};
const worker = new Worker(options);
// according to specs I should see DedicatedWorkerGlobalScope.name === 'my-worker' when debugging
```

However looking at the [code here](https://github.com/webpack-contrib/worker-loader/blob/master/src/workers/InlineWorker.js#L27), it does not seem possible.

Which pieces of code should be modified to handle this?

**Comment by llorllale** [comment]
The README says this plugin loads scripts as *Web Workers* (client), not worker threads (nodejs). What you're asking for is a worker_threads feature.

Or did I get this wrong and this plugin also supports worker threads?

**Comment by evilebottnawi** [comment]
Done in master, now you can set worker options via the `worker` option, docs will be updated in the near future, sorry for delay
