### ISSUE TITLE
Worklet support?

### ISSUE THREAD

**Issue by hughrawlinson** [webpack-contrib/worker-loader#163]
Would worklet support be something of interest for this package? The worklets have generally pretty similar interfaces to the worker, so I'm interested in seeing if it'd be possible to set the constructor you use?

**Comment by gaoryrt** [comment]
https://github.com/reklawnos/worklet-loader may help

**Comment by evilebottnawi** [comment]
Sorry for delay, yes, PR welcome, we can move logic from `worklet-loader` into `worker-loader`

**Comment by alexander-akait** [comment]
Supported by webpack@5 by default https://github.com/webpack/webpack/issues/11543#issuecomment-745529334
