### ISSUE TITLE
wrong paths using dynamic imports in workers

### ISSUE THREAD

**Issue by flo-l** [webpack-contrib/worker-loader#164]
I'm getting 404s when using dynamic import in a worker. I'm not sure if this is supposed to work, I'm just starting with webworkers. But it seems odd to get a 404 instead of, eg. an error message telling me what I do doesn't work.

I created a minimal project for reproduction of the problem [here](https://github.com/flo-l/worker-loader-bugreport). It contains all details + code. If more info is needed feel free to ask.

Thanks in advance for investigating this.

**Comment by flo-l** [comment]
maybe related?

webpack/webpack#7529

**Comment by flo-l** [comment]
also maybe related:

webpack/webpack#4861

**Comment by evilebottnawi** [comment]
You should not create `new Worker()`, because loader do it for you, I will improve examples
