### ISSUE TITLE
Uncaught ReferenceError: window is not defined

### ISSUE THREAD

**Issue by snoopy1412** [webpack-contrib/worker-loader#166]
when I set worker-loader in creat-react-app , I received this error waring

the codes are all the same with the official sample;

 "worker-loader": "^2.0.0"
"webpack": "4.19.1",

**Comment by jiechud** [comment]
@snoopy1412  
add  globalObject : 'this' 
You can go look   https://github.com/webpack/webpack/issues/6642

**Comment by seanpkent** [comment]
As this is not the default option in webpack, it would be nice to see this in the documentation.
I case anyone is wondering, `globalObject` option goes in the `output` options in webpack config. 
For example:
`output: {
       path: path.join(__dirname, 'dist'),
       filename: 'bundle.js'
       publicPath: 'http://localhost:3000',
       globalObject: 'this'
},`

**Comment by davidawad** [comment]
Came up against this when trying to implement the final comment on this issue with CRA:   https://github.com/facebook/create-react-app/issues/1574

For anyone that happens to find this that is trying to use EpubJS in create react app and can't get the service worker imported properly, the ONLY thing that worked for me was to eject the app from CRA and add `globalObject: 'this'` to the webpack config myself. 

If you're reading this out of desperation, I feel your pain... god speed.

**Comment by brettimus** [comment]
so in case anyone bumps into something similar, our worker broke because a file that it depended on was importing something that in turn imported CSS, and the `style-loader` uses the window object.

very silly regression. but hey. it happened.

**Comment by ahuglajbclajep** [comment]
This problem seems to be the same one as #142.

**Comment by evilebottnawi** [comment]
Close in favor #174
