### ISSUE TITLE
Syntax Error in IE 11

### ISSUE THREAD

**Issue by bart-1990** [webpack-contrib/worker-loader#169]
The loader doesn't seem to work properly in IE11. 

I am using the following config:

```
module: {
		rules: [			
			{
				test: /\.worker\.js$/,
				loader: 'worker-loader'
			}
                   ]
}
```

When I create the web worker like this:
```
import Worker from './my-worker.worker.js';
const worker = new Worker();
```
IE11 throws the error:
SCRIPT0: SYNTAX ERROR

Can someone confirm this error or is there something I should add to my babel config or do I need some sort of polyfill?

**Comment by minlare** [comment]
I also recieve this error.

**Comment by Aymkdn** [comment]
With Vue, in `vue.js.config` you can do the below to make it loaded by Babel:
```javascript
chainWebpack: config => {
    config.module
    .rule('babel-worker')
    .test(/\.worker\.js$/)
    .use('babel-loader')
    .loader('babel-loader')
    .end();
}
```

**Comment by evilebottnawi** [comment]
You need setup babel-loader for new syntax, example above, I will update docs soon
