### ISSUE TITLE
Compatibility with webpack-dev-server HMR.

### ISSUE THREAD

**Issue by aprilmintacpineda** [webpack-contrib/worker-loader#174]
![image](https://user-images.githubusercontent.com/21032419/49852829-2ea87280-fe20-11e8-9e01-aedee773a580.png)

![image](https://user-images.githubusercontent.com/21032419/49853099-09683400-fe21-11e8-9202-42db71c8811e.png)

The error is coming from the web worker because `window` is not available on web workers.

Turning off HMR will fix the error BUT I want to be able to use HMR for other stuff. Is there anything that the loader could do about this?

https://github.com/webpack/webpack-dev-server/issues/1595

**Comment by ethansisson** [comment]
I'm also experiencing this issue.

**Comment by spencer-brown** [comment]
jFYI - a workaround has been recommended on the Webpack side [here](https://github.com/webpack/webpack/issues/6642#issuecomment-417581675).

**Comment by masx200** [comment]
'm also experiencing this issue

**Comment by masx200** [comment]
output: {
       path: path.join(__dirname, 'dist'),
       filename: 'bundle.js'
       publicPath: 'http://localhost:3000',
       globalObject: 'this'
},

**Comment by masx200** [comment]
https://github.com/webpack/webpack-dev-server/issues/1595


https://github.com/webpack/webpack/issues/6642

https://github.com/webpack-contrib/worker-loader/issues/174

**Comment by evilebottnawi** [comment]
Somebody can create minimum reproducible test repo?

**Comment by kumar303** [comment]
@evilebottnawi I don't know if it's very minimal but I used [create-react-app](https://facebook.github.io/create-react-app/) to make a simple example. https://github.com/kumar303/worker-loader-issue174

The readme has instructions. The app gives me: `ReferenceError: window is not defined`

If I understand correctly, I can change the webpack config to transform `window` into `this` but that's tricky with create-react-app. I'm still thinking of ways to solve it.

**Comment by evilebottnawi** [comment]
@kumar303 it is happens only with webpack-dev-server?

**Comment by kumar303** [comment]
yes, I think so. In create-react-app, `yarn start` starts up in development mode.

**Comment by evilebottnawi** [comment]
@kumar303 if is happens only with webpack-dev-server, can you create issue in webpack-dev-server repo with reproducible test repo (no need minimum, just step how to reproduce problem)

**Comment by kumar303** [comment]
The title is misleading but this issue already exists in webpack-dev-server; it seems to be about the same exact problem: https://github.com/webpack/webpack-dev-server/issues/1595

**Comment by evilebottnawi** [comment]
@kumar303 i think we should solve this instead exclude some files from HMR, because it is not good solution

**Comment by evilebottnawi** [comment]
Can you put example with reproachable steps in issue

**Comment by davidawad** [comment]
I've been fighting with this issue for a few days. I can't seem to include pdfjs within create react app. 

See https://github.com/wojtekmaj/react-pdf/issues/190 https://github.com/developit/workerize-loader/issues/5 and https://github.com/facebook/create-react-app/issues/1574

**Comment by evilebottnawi** [comment]
I will look this on weekend

**Comment by dangreen** [comment]
Hi there 👋

This is my solution to disable HMR for workers:
https://github.com/TrigenSoftware/hmr-filter-webpack-plugin#usage

**Comment by evilebottnawi** [comment]
Fixed in the master, ETA is the end of week, big sorry for delay
