### ISSUE TITLE
Can a web worker script import other libraries?

### ISSUE THREAD

**Issue by stoplion** [webpack-contrib/worker-loader#179]
Can a web worker script import other libraries?
Asking because as soon as I do, the compilation runs out of memory and errors out

**Comment by stoplion** [comment]
thanks!

**Comment by koriner** [comment]
@stoplion I'm running into this exact same issue. Trying to import a file from the app codebase inside my worker file causes webpack/node to just build forever and runs out of memory.

Did you have to do anything specific to get around this?

**Comment by stoplion** [comment]
Unfortunately I never figured out how to get it work.

**Comment by buffaybu** [comment]
I met this problem today and it worked after I removed circular imports.

```js
// main.js
import MyWorker from './worker.js'
export const messageTypes = { /* ... */ }
```

```js
// worker.js
import { messageTypes } from './main.js' // this is the cause
```
