### ISSUE TITLE
Worker-loader web worker not working with Webpack 4

### ISSUE THREAD

**Issue by JavaJamie** [webpack-contrib/worker-loader#183]
We've successfully created a web worker using worker-loader in a CRA project using Webpack 3.5.6 and it's worked fine but upon upgrading it to Webpack 4.19.1 it doesn't worked. It results in a worker.postMessage is not a function error. We have tried absolutely everything in terms of re-ordering the code, scopes etc but to no avail. After doing research it appear this is a very widespread issue.

**Comment by stoplion** [comment]
Having same issue.

**Comment by evilebottnawi** [comment]
Sorry, I can't help, information is not enough, we have tests on  `puppeteer` and all works fine, maybe something on CRA side, I close this issue, but feel free to open a new issue with minimum reproducible test repo if you faced with issue again
