### ISSUE TITLE
Worker polyfills

### ISSUE THREAD

**Issue by the-spyke** [webpack-contrib/worker-loader#184]
Is there a way to add polyfills automatically? Usually I add an additional entry point in Webpack config pointing to `babel-polyfill`. This is convenient when you need to build different versions of the package: complete for a demo or browser, unpolyfilled for npm, etc. How to solve this problem for web workers?

**Comment by evilebottnawi** [comment]
@the-spyke use multicompiler mode

**Comment by the-spyke** [comment]
@evilebottnawi I'm using it. The first one has `babel-polyfill` entry and the second one hasn't. How to add polyfill to workers in first compiler?

**Comment by evilebottnawi** [comment]
@the-spyke setup `.babelrc`/`babel.config.js` for `babel-loader` on first compilation

**Comment by evilebottnawi** [comment]
Also it is bug tracker, not QA service, better use for question `stackoverflow`/`gitter`

**Comment by the-spyke** [comment]
@evilebottnawi The issue that I'm describing exists without multi-compiler too. If I have a single build with polyfill entries and I do not use Babel's `built-ins` mode when it overrides `Object.entries()` with it's own calls. Who will copy polyfill code from main chunk to worker chunk?

**Comment by piotrblasiak** [comment]
@the-spyke were you able to find a solution to this?

**Comment by the-spyke** [comment]
@piotrblasiak No, I wasn't and rewrote worker code so it works without polyfills everywhere.

**Comment by Aymkdn** [comment]
See https://github.com/webpack-contrib/worker-loader/issues/169#issuecomment-615121811 and https://github.com/webpack-contrib/worker-loader/issues/195#issuecomment-615123513

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack-contrib/worker-loader/issues/253, I will put example
