### ISSUE TITLE
Failed to load resource

### ISSUE THREAD

**Issue by aprilmintacpineda** [webpack-contrib/worker-loader#185]
![image](https://user-images.githubusercontent.com/21032419/51722122-52054500-208f-11e9-8bda-6cf6fc8bb231.png)

![image](https://user-images.githubusercontent.com/21032419/51722151-66e1d880-208f-11e9-9870-7a3de3e38838.png)

In the images above, you see that loading the file itself failed due to network errors.

- Is there any way to handle such error so that recovery procedures could be performed?
- I also noticed that every time the worker is created, the file is requested to the network instead of from cache even if it has been requested before. Is there any way to get around this and simply load them from cache instead of from network?

**Comment by evilebottnawi** [comment]
> Is there any way to handle such error so that recovery procedures could be performed?

yes can achieve this using code `function loadWorker { return import('worker.js'),then(m => m).catch(e => { console.log(e); loadWorker(); })}`, you can improve this using based on logic of your app

> I also noticed that every time the worker is created, the file is requested to the network instead of from cache even if it has been requested before. Is there any way to get around this and simply load them from cache instead of from network?

You need to setup your web server for this
