### ISSUE TITLE
class Arrow function worker faild

### ISSUE THREAD

**Issue by gwmaster** [webpack-contrib/worker-loader#187]
import _ from 'lodash'
class MyWorker{
    constructor(){
        self.addEventListener('message', this.onMessage)
    }
    onMessage = (event) => {
        debugger
    }
}
new MyWorker()

manager.worker.js
    Module parse failed: Unexpected token (7:14)
    You may need an appropriate loader to handle this file type.
    |         self.addEventListener('message', this.onMessage)
    |     }
    |     onMessage = (event) => {
    |         debugger
    |     }

**Comment by evilebottnawi** [comment]
Sorry I can't update the issue, feel free to open a new issue with more information
