### ISSUE TITLE
ctx.postMessage doesn't work (TypeScript)

### ISSUE THREAD

**Issue by mehmetnyarar** [webpack-contrib/worker-loader#189]
Hi,

I am in an ejected CRA app with TypeScript. I can send message from component to  the worker, worker successfully takes the input data, processes it but `ctx.postMessage` seems does nothing, therefore I cannot get the result from the worker.

Here are the steps I took:

1. I added `worker-loader` to the `config/webpack.config.js`:

```js
{
  test: /\.worker\.ts$/,
  use: {  loader: 'worker-loader' }
},
```

2. I added below to my `custom.d.ts`:

```typescript
declare module "worker-loader!*" {
  class WebpackWorker extends Worker {
    constructor();
  }

  export default WebpackWorker;
}
```

3. My worker:

```typescript

import { getThis, getThat, Model } from '@features/feature'

const ctx: Worker = self as any

ctx.addEventListener('message', e => {
  const result: Model[] = []
  const { param1, param2 } = e.data

  // ...
  // long process
  // ...

  ctx.postMessage(result) // Does nothing
})

```

4. I import the worker in my component:

```typescript
import MyWorker from 'worker-loader!./worker/my.worker'

class MyComponent extends React.Component<Props, State> {
  worker?: MyWorker

  componentDidMount  () {
    this.worker = new MyWorker()
  }

  componentDidUpdate () {
    let condition = true // let's say so
    if (condition && this.worker) {
      const { param1, param2 } = this.props

     // I can't get anything from worker
      this.worker.onmessage = e => {
        console.log('worker onmessage', e)
      }
      this.worker.onerror = e => {
        console.log('worker onerror', e)
      }
      this.worker.addEventListener('message', e => {
        console.log('worker message listener', e)
      })

      // This works
      this.worker.postMessage({ param1, param2 })
    }
  }
}
```

[Here](https://textuploader.com/1516h) is my `package.json`
[Here](https://textuploader.com/1516g) is my `tsconfig.json`

I'd appreciate for any help.

Related conversations:

- [Problems using Typescript and WebWorkers together](https://github.com/webpack-contrib/worker-loader/issues/94#issuecomment-394333019)
- [Add WebWorker Support ](https://github.com/facebook/create-react-app/issues/3660)
- [Add support for WebWorker with worker-loader](https://github.com/facebook/create-react-app/issues/3660)

**Comment by lckj210** [comment]
I just encountered the same problem. It turned out that there is no need to do step 1...

**Comment by Cosmet** [comment]
I also ran into this issue and removed the worker-loader from step 1 as @jasonlaw-dev suggested. Seems to work now.

**Comment by Cosmet** [comment]
I ran into the same issue. Removing the worker-loader from webpack.config as @jasonlaw-dev suggested seems to have worked.

**Comment by nishio** [comment]
I just made a tutorial to collaborate with CRA + TypeScript:

https://github.com/nishio/tutorial-webworker-with-react/blob/master/README.md

**Comment by nishio** [comment]
I agree to drop the step 1, because you use webpack-loader-syntax in the import statement of step 4:
`import MyWorker from 'worker-loader!./worker/my.worker'`

I also did the same.

**Comment by evilebottnawi** [comment]
Problem on CRA side and typescript, here good example https://github.com/nishio/tutorial-webworker-with-react/blob/master/README.md, sorry but we can something here on our side, sorry for delay
