### ISSUE TITLE
No options being used

### ISSUE THREAD

**Issue by danikaze** [webpack-contrib/worker-loader#192]
Basically, I'm trying to use `worker-loader` in an Electron + Next.js app, with webpack, via `next-workers`.

This `next-workers` basically adds this rule to webpack:
```js
{
  test: /\.worker\.js$/,
  use: {
    loader: 'worker-loader',
    options: nextConfig.workerLoaderOptions || {
      name: 'static/[hash].worker.js',
      publicPath: '/_next/'
    },
  },
}
```

But it's not working. `worker-loader` is being called properly but it looks like the options are ignored.
After struggling some time, I tried to _debug_ it and just displayed the options being used inside `node_modules/worker-loader/dist/index.js`

```js
// node_modules/worker-loader/dist/index.js
const options = _loaderUtils2.default.getOptions(this) || {};
console.log('worker-loader options', JSON.stringify(options, null, 2));
```

resulting in an empty object:
> worker-loader options {}

Any reason of why is this happening, or how could I solve it?

### System Info
Node js version: 8.11.3
worker-loader: 2.0.0

**Comment by Dancia** [comment]
Same issue. No options being used at all.

Node: v10.11.0
worker-loader: 2.0.0

**Comment by masterkidan** [comment]
Same issue
Note: v8.11.3
worker-loader: 2.0.0

**Comment by evilebottnawi** [comment]
Bug on `next` side, feel free to open a new issue in `next` repo

**Comment by masterkidan** [comment]
@evilebottnawi I think it would be helpful if you could explain why you think it is a bug on the next side?

**Comment by evilebottnawi** [comment]
We have tests and options are works in tests, so problem on boileplate side, you can create reproducible test repo and I can help to restiveness where is bug
