### ISSUE TITLE
wrong worker js file is loaded

### ISSUE THREAD

**Issue by 0x53A** [webpack-contrib/worker-loader#194]
worker-loader created two files:

``576e8350095daa76e57a.worker.js``

```
... {e.exports=function(){return new Worker(t.p+"5aed48f4f2b2d95b6440.worker.js")}}});
```

``5aed48f4f2b2d95b6440.worker.js``

```
self.onmessage=function(e){console.log("[WORKER-JS] Message:",e),r(e)}}});
```

------------

then in main.js, where I import the worker like this: ``worker-loader!./../Client.Worker/client.worker.js``

```
return new Worker(n.p+"576e8350095daa76e57a.worker.js"
```

So it tries to create a worker from the wrong js file.

**Comment by evilebottnawi** [comment]
Something wrong with the configuration, feel free to post it here and I will be help you, closing now
