### ISSUE TITLE
how to set tree-shaking config

### ISSUE THREAD

**Issue by zhu1033527427** [webpack-contrib/worker-loader#196]
A.js
```
export function fa() {
     ...
}

export function fb() {
     ...
}

export function fc() {
     ...
}
....
```
*.worker.js

```
import { fa } from 'A.js';
....

```

In *.worker.js，i import some function or method that i need, but when i build it, it include some other useless code (example: fb, fc) in builded file

**Comment by evilebottnawi** [comment]
webpack already do this

**Comment by zhu1033527427** [comment]
> webpack already do this

It doesn't work in *.work.js!

**Comment by evilebottnawi** [comment]
Answer here https://github.com/webpack-contrib/worker-loader/issues/132#issuecomment-415721860, we need to document it
