### ISSUE TITLE
Worker file not emitted with nested imports

### ISSUE THREAD

**Issue by wanecek** [webpack-contrib/worker-loader#197]
Whenever importing a worker-file that in turn imports another file, the main worker file is not emitted in the build. 

I've created a reproducible test case at [wanecek/vue-worker-loader-test@broken-nested-import](https://github.com/wanecek/vue-worker-loader-test/tree/broken-nested-import), with the following structure:

- **main.js**, "normal" JS-land, which `import(...)`s example.worker.js
- **example.worker.js**, with onmessage and postMessage functions. In turn imports second-import.js
- **second-import.js**, dummy javascript.

This results in two chunks:

Main chunk (from main.js and related contents), which imports...
example.worker.[hash].js, which tries to import a non-existing `[hash].worker.js` file.

---

OS: Ubuntu 18.10
Node: 11.13.0
worker-loader: 2.0.0

**Comment by wanecek** [comment]
This may be related to #194, but I'm not sure. 

@evilebottnawi, let me know if there's anything I can do to help you debug this.

**Comment by Pomevak** [comment]
I am having the same problem, did you solve it?

**Comment by Finesse** [comment]
I has the same issue. I fixed it by removing the loader option:

```diff
{
  test: /\.worker\.[^.]+$/,
  use: {
    loader: 'worker-loader',
    options: {
      inline: false,
-     fallback: false,
    },
  },
},
```

**Comment by evilebottnawi** [comment]
It was bug on `vue-cli` side, it is not respect options for loaders, should be fixed, if you faced with the issue again, feel free to open the new issue with minimum reproducible test repo, sorry for delay
