### ISSUE TITLE
Wrong path generated for chunked worker files

### ISSUE THREAD

**Issue by sabubaker** [webpack-contrib/worker-loader#199]
When a custom path is specified for emitted worker files as follows:

`loader: require.resolve("worker-loader"),`
`options: {`
`    name: 'static/js/Custom.[hash].worker.js',`
`    publicPath: "/static/js/"`
`}`

the output is as expected as long as the workers do not have chunked files. However, when they do contain chunks, the output is as follows:

`1.08 KB        build\static\js\Custom.1d4ad84aa77f190d8b23.worker.js`
`717.74 KB      build\1.static\js\Custom.1d4ad84aa77f190d8b23.worker.js`
`649.83 KB      build\2.static\js\Custom.1d4ad84aa77f190d8b23.worker.js`

As seen above, the first non-chunked worker file is placed in the `static/js` folder as expected but the chunked worker files are placed in `1.static\js` and `2.static\js` folders respectively.

This occurs because of the following code in `index.js`:

`  worker.options = {`
`    filename,`
`    chunkFilename: `[id].${filename}`,`
`    namedChunkFilename: null,`
`  };`

where the `[id]` is tacked on in the `chunkFilename` without accounting for the fact that there may be a custom path specified - as supported by webpack.

This makes it impossible to emit chunked worker files to a desired directory which may be needed to apply caching headers to all static files, for instance.

**Comment by VictorWu90** [comment]
+1

**Comment by serkanyersen** [comment]
I'm having the same problem.

**Comment by ianberdin** [comment]
+1
