### ISSUE TITLE
[Feature] support `SharedWorker`

### ISSUE THREAD

**Issue by arypurnomoz** [webpack-contrib/worker-loader#2]

**Comment by gustafnk** [comment]
:+1:

**Comment by sokra** [comment]
PR?

**Comment by gustafnk** [comment]
Nope :(

But I actually think it will work OOTB if a configuration would be added so that https://github.com/webpack/worker-loader/blob/master/index.js#L40 could be parameterized to allow both SharedWorker and Worker.

I have a use case where I'm using a SharedWorker, so I can easily test when I get time.

**Comment by boogerlad** [comment]
#32

**Comment by jiechud** [comment]
Is the plan going

**Comment by InstanceOfMichael** [comment]
I'm going to try this: https://www.npmjs.com/package/shared-worker-loader

**Comment by indus** [comment]
serious? over 4 years for a conditional switch and it is still not available. I don't get the problem.

**Comment by indus** [comment]
Until this feature gets implemented I'm using the following monkey patch:

``` JS
import MyWorker from './MyWorker.worker';
let myWorker = new MyWorker();

let createSharedWorkerClass = function (workerFn): any {
  let fn = workerFn.toString();
  let fnBody = fn.slice(fn.indexOf('{') + 1, fn.lastIndexOf('}'));
  let fnBodyShared = '__webpack_require__ = {p:path};' + fnBody.replace('Worker', 'SharedWorker');
  return new Function('path', fnBodyShared);
}

const MySharedWorker = createSharedWorkerClass(MyWorker);
let mySharedWorker = new MySharedWorker();
```

**Comment by Tvinsh** [comment]
@indus I have the same question, can you show the code in MyWorker.worker

**Comment by indus** [comment]
@Tvinsh I'm not sure I get you right. The function produced by Webpack looks like so:
```
function() {
  return new Worker(__webpack_require__.p + "ae8bdc45b9c5982df0eb.worker.js");
}
```

If you are interested in code that lets you use a WebWorker  as Shared worker as well, then I can only present you this TS-fragment:
``` ts
const ctx: any = self as any;

declare namespace global {
    let window: Worker
};

let ports = [ctx];

ctx.onmessage = ev => {
    let { type, data } = ev.data;
    switch (type) {
        case 'init':
            console.log('init');
            break;
        default:
            console.log(ev.data);
            break;
    }

    //ports.forEach(p => p.postMessage({ type: null, data: type }));
}


try {
    //@ts-ignore //SharedWorker
    onconnect = e => {
        var port = e.ports[0];
        port.onmessage = ctx.onmessage;
        ports[0] == ctx ? ports = [port] : ports.push(port);

    }
} catch { }

export default {} as typeof Worker & { new(): Worker };
```
The idea is that onconnect only gets used in Sharedworkers and could result in multiple ports that my want to get every message (my use-case). So by putting them in an array I'm able to use forEach to post to all of them. In it is just a normal webworker I have the array of ports is prefilled with only the webworker itself.
I would like to get rid of the try-catch block but havn't found a way.

**Comment by Tvinsh** [comment]
@indus Thank you, I will try again to see if I can handle it

**Comment by skmvasu** [comment]
Hi @sokra  Are there any plans of merging is? If no, is there any issue in this approach? Happy to work on fixing them if there are any blockers in this approach. This will help me out in some of my projects.

**Comment by evilebottnawi** [comment]
Fixed https://github.com/webpack-contrib/worker-loader/pull/247
