### ISSUE TITLE
Async worker loading

### ISSUE THREAD

**Issue by DioNNiS** [webpack-contrib/worker-loader#202]
I'm using TypeScript approach to load worker (https://github.com/webpack-contrib/worker-loader#integrating-with-typescript).
It seems that worker loaded syncroniusly. 
How I can make it asyncroniusly, so that my main app whould not wait untill worker is loaded?

**Comment by DioNNiS** [comment]
Can I load worker dynamicly?

```
...
import(/* webpackChunkName: "worker" */ "worker-loader!./Worker").then((worker: any) => {
    const worker = new Worker();

    worker.onmessage = (event: MessageEvent) => {
     ...
    };
  });
...
```

`const worker = new Worker();` - is not a constructor in this case....
How to make it properly?

**Comment by mityok** [comment]
@DioNNiS did you managed to solve the issue, I'm having the same problem

**Comment by TNieminen** [comment]
Also having this issue, would love to hear some thoughts on this!

**Comment by Tarik02** [comment]
Did you try something like this?
```
import(/* webpackChunkName: "worker" */ "worker-loader!./Worker").then((MyWorker: any) => {
    const worker = new MyWorker();

    worker.onmessage = (event: MessageEvent) => {
     ...
    };
  });
```

**Comment by TNieminen** [comment]
Got it to work on my local as

```js
import(/* webpackChunkName: "myWorker.js" */ './myWorker.js')
        .then(myWorker => myWorker.default)
        .then((myWorker) => myWorker())
```
I'm a bit confused why I got returned a function, but does seems to work.
Return of the import:

```js
return new Worker(__webpack_require__.p + "js/worker.561c6da5ed9fd323a9d7.js");
```

I was however unable to bundle this with webpack the import elsewhere. But I guess that is just a matter of webworkers not being available in my servers dist? Something that I could fix with publicPath maybe?

**Comment by YuhangGe** [comment]
Found a solution for typescript@^3.8.3

````js
//  typings/custom.d.ts
declare module 'worker-loader!*' {
  interface WorkerConstructor {
    new(): Worker;
  }

  export = WorkerConstructor;
}

````

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack-contrib/worker-loader/issues/253, we need improve examples, I will do it in near future
