### ISSUE TITLE
Build breaks when dev dependencies are installed

### ISSUE THREAD

**Issue by liamcarter111** [webpack-contrib/worker-loader#203]
When running with dev dependencies installed (to make project contributions) the parent webpack project build fails with:

> ..\worker-loader\node_modules\webpack\lib\webworker\WebWorkerMainTemplatePlugin.js:97
                        hash.update(`${this.outputOptions.publicPath}`);
TypeError: Cannot read property 'outputOptions' of undefined
    at ..\worker-loader\node_modules\webpack\lib\webworker\WebWorkerMainTemplatePlugin.js:97:24

Works fine when updating project dev dependencies to webpack: "^4.0.0".
**Submitting PR.**

**Comment by evilebottnawi** [comment]
Fixed
