### ISSUE TITLE
Memory leak resulting in net::ERR_OUT_OF_MEMORY

### ISSUE THREAD

**Issue by michal-lipski** [webpack-contrib/worker-loader#208]
**The problem**

The loader is calling `URL.createObjectURL` to create URL representing the worker javascript bundle file. The object is never released, and garbage collector can't remove it from memory.
At some point it is not possible to create another object and error is thrown: `net::ERR_OUT_OF_MEMORY` which means the buffer of the network interface is full.

I am getting this on all browsers.

**Proposed solution**

 According to [documentation](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL), we can call `revokeObjectURL()` to release an object URL.

`````     
const objectUrl = URL.createObjectURL(blob);  
const worker = new Worker(objectUrl);  
URL.revokeObjectURL(objectUrl);  
return worker;  
`````

**Comment by evilebottnawi** [comment]
PR welcome
