### ISSUE TITLE
Use in Cordova

### ISSUE THREAD

**Issue by atgillette** [webpack-contrib/worker-loader#21]
Hi,

Has anyone got web workers to work in a cordova context?  When I take a look at the js resources loaded into IOS app, I don't see a file for the web worker.

**Comment by michael-ciniawsky** [comment]
@atgillette Is this a general question about `WebWorker` support in a Cordova App or related to `worker-loader` in particular, if the first please use StackOverflow or the main brain (e.g Google) instead :)
