### ISSUE TITLE
What does fallback mode do?

### ISSUE THREAD

**Issue by trusktr** [webpack-contrib/worker-loader#210]
Does it polyfill `worker.postMessage` to work on code running in the same thread (not a worker)?

**Comment by evilebottnawi** [comment]
Require a fallback for non-worker supporting environments

**Comment by trusktr** [comment]
@evilebottnawi I get that part. But what does it do? Is it going to add a polyfill, so that code that is calling `worker.postMessage()` will be faked?

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack-contrib/worker-loader/issues/253, should be in README
