### ISSUE TITLE
PublicPath is not working in Production Mode

### ISSUE THREAD

**Issue by geethu-u** [webpack-contrib/worker-loader#211]
I am specifying publicPath as /js/ so that the output of worker goes to the js folder along with my other build files. However, it's not going there. Also, I'm getting an error in console saying 
excelReaderWorker.js:2 GET http://127.0.0.1:8887/cpoupload/cbfd9ad385e82500bb79.worker.js 404 (Not Found)

{
        test: /\.worker.js$/,
        exclude: /node_modules/,
        loader: 'worker-loader',
        options: { inline: true, fallback: false , publicPath: '/js/' , name: 'excelReader.[hash].worker.js'} 
      }

I'm able to get webworker working in my localhost. This only happens when i create build.

**Comment by MrPlume2** [comment]
i have the same question

**Comment by geethu-u** [comment]
Is someone looking into this?

**Comment by evilebottnawi** [comment]
You need to set `fallback: true`, I will improve this, it doesn't have sense when you use `fallback: false` together with `publicPath` or `name`
