### ISSUE TITLE
Worker-loader not using specified options

### ISSUE THREAD

**Issue by altinselimi** [webpack-contrib/worker-loader#212]
I am using v2.0.1 of the plugin, and have followed setup options properly for using it inside a Vue JS project. Its working well in development mode, but when bundling for production its not respecting the configuration that I have got in vue.config.js. 
```
module.exports = {
  parallel: false,
  chainWebpack: (config) => {
    config.output
      .globalObject('this')
    config.module
      .rule('worker')
      .test(/\.worker\.js$/i)
      .use('worker-loader')
      .loader('worker-loader')
      .tap(options => {
        return {
          fallback: false,
          inline: true,
          name: 'MyWorker.[hash].js'
        };
      })
      .end()
  },
};
```
I have confirmed Vue is outputting the proper configuration by running `vue inspect > output.js` which is outputting this configuration for the worker-loader module:
```
/* config.module.rule('worker') */
{
  test: /\.worker\.js$/i,
  use: [
    /* config.module.rule('worker').use('worker-loader') */
    {
      loader: 'worker-loader',
      options: {
        fallback: false,
        inline: true,
        name: 'MyWorker.[hash].js'
      }
    }
  ]
}
```
This is still outputting separate files (not inline) and `MyWorker` does not appear on any of the generated `.worker.js` files.

Can you point me in the right direction on this one ?

Thanks !

**Comment by epirovano** [comment]
Same problem, I'm using the publicPath  and name options but are ignored.
Have you figured out this problem?

thanks!

**Comment by altinselimi** [comment]
Nope, can't figure it out myself...

**Comment by zachwinter** [comment]
I'm also unable to `tap` in configuration options using @vli/cli.

**Comment by mervynyang** [comment]
Same problem, all options are ignored.

**Comment by altinselimi** [comment]
Guys, I succeeded by using rollup for bundling my library. You should try that out. Nothing in the webpack land seemed to work.

**Comment by ericblade** [comment]
no options working here, either.  no idea what might be the issue.  

With little dev on this in almost 2 years, and pull reqs mounting up, i'm guessing this is not stable, functional, or still in active development... :(

**Comment by evilebottnawi** [comment]
Fixed in the master, you don't need the `name` option when you set `fallback: false`, this makes no sense, I will improve error helping

**Comment by UziTech** [comment]
@evilebottnawi when can we expect a release with this fix?

**Comment by evilebottnawi** [comment]
@UziTech ETA is the current week
