### ISSUE TITLE
Lag in loading the web worker.js by the browser

### ISSUE THREAD

**Issue by luxsush** [webpack-contrib/worker-loader#214]
Hi, 

I am facing this problem where the web-worker.js is loaded around 200-300 ms after the rest of the main thread ina Chrome browser.  How can I ensure parallel load ?

My app needs to make a call to the web worker on load but now it has to wait 200-300ms before it can send the first request making my app look slow

![image](https://user-images.githubusercontent.com/16308363/64675408-6d349180-d473-11e9-90b3-99736e1164d9.png)

**Comment by jzombie** [comment]
Try running it as an inline-blob.

e.g.
`
{
  loader: 'worker-loader',
  options: { inline: true }
}
`

**Comment by evilebottnawi** [comment]
You can implement this on app side, using `import('my.worker.js').then((m) => /* Logic */)`
