### ISSUE TITLE
Google's worker-plugin is good alternative to this package

### ISSUE THREAD

**Issue by jzombie** [webpack-contrib/worker-loader#216]
https://github.com/GoogleChromeLabs/worker-plugin

**Comment by evilebottnawi** [comment]
Yes

**Comment by ValkoVolodya** [comment]
But it works only with webpack v4+ as far as I know(

**Comment by evilebottnawi** [comment]
webpack@3 is deprecated and we strongly recommend to update

**Comment by piotrblasiak** [comment]
Does not support inline workers yet...

**Comment by evilebottnawi** [comment]
We starting to upgrade `worker-loader` and provide first class support, so a lot of features + fixes will be here
