### ISSUE TITLE
Minimal example of a working TypeScript ES6 Webpack setup not working

### ISSUE THREAD

**Issue by marcusegues** [webpack-contrib/worker-loader#221]
I can't get worker-loader to work perfectly with TypeScript and ES6 from the docs.

I've set up a [repo](https://github.com/marcusegues/worker-loader-test) with the minimal setup to potentially get this to work.

It uses webpack on an entry file called `index.ts` that imports Worker from a worker file as described in the docs.

```
import Worker from "worker-loader!./my.worker.ts";

console.log("Spawning new worker", Worker);
const worker = new Worker();

worker.onmessage = (e: any) => {
  console.log("Received data in main thread", e.data);
};
```

The error I get in my chrome devtools is that `r.default is not a constructor`. The error I get in TypeScript is `Error:(1, 20) TS2307: Cannot find module 'worker-loader!./my.worker`. 

The first console log above shows that Worker is `undefined`.

What am I missing here?

**Comment by alk831** [comment]
Same issue with `create-react-app` project.

**Comment by nishio** [comment]
I made a minimal sample of React + TypeScript.

https://github.com/nishio/tutorial-webworker-with-react/blob/master/README.md

You need to add custom type definition.

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack-contrib/worker-loader/issues/253
