### ISSUE TITLE
Add a worker implementation based on fetch

### ISSUE THREAD

**Issue by otakustay** [webpack-contrib/worker-loader#225]
We were using `worker-loader` and encountered CORS issue, the `inline` option works but make bundle much larger.

I'm wondering if we can provide a `FetchWorker` like:

```js
const fetchWorker = url => {
    const pendingMessages = [];
    const listeners = [];
    let worker = null;

    const newWorker = text => {
        worker = inlineWorker(text, url);
        for (const [message, transferList] of pendingMessages) {
            worker.postMessage(message, transferList);
        }
        pendingMessages.length = 0;
    };

    fetch(url).then(r => r.text()).then(newWorker);

    return {
        postMessage(message, transferList) {
            if (worker) {
                worker.postMessage(message, transferList);
            }
            else {
                pendingMessages.push([message, transferList]);
            }
        },

        addEventListener() {
            // ...
        }
    }
}
```

With this implementation we can move worker to a separated file just like `inline` is disabled, but read it via `fetch` to come across CORS issue.

**Comment by otakustay** [comment]
Or this can be implemented via `importScripts` function

**Comment by evilebottnawi** [comment]
https://github.com/webpack-contrib/worker-loader/pull/255, you can set credentials vie options

**Comment by otakustay** [comment]
It seems `credentials` option does not address cors issues, worker doesn't support cors script no matter what `credentials` is.

**Comment by evilebottnawi** [comment]
I can't understand the problem

> We were using worker-loader and encountered CORS issue

What?

> I'm wondering if we can provide a FetchWorker like:

It is out of scope web worker supporting

**Comment by otakustay** [comment]
When `publicPath` is set to an external domain like `http://cdn.my-app.com/assets/`, worker-loader generated worker script can fail to load, just as documented: https://github.com/webpack-contrib/worker-loader#cross-origin-policy

To address this, document suggests `inline` option but this increase bundle size impressively

There is a way to get rid of the CORS issue and having worker scripts in a separated bundle if worker-loader can generate its content to a custom blob and a `importScripts` call according to this article: https://benohead.com/blog/2017/12/06/cross-domain-cross-browser-web-workers/

**Comment by evilebottnawi** [comment]
I think we can do it, do you want to send a PR?

**Comment by evilebottnawi** [comment]
Let's close in favor https://github.com/webpack-contrib/worker-loader/issues/281, I think solution here https://benohead.com/blog/2017/12/06/cross-domain-cross-browser-web-workers/ is good
