### ISSUE TITLE
[Feature Request]: Why does not the loader return the worker path?

### ISSUE THREAD

**Issue by wood1986** [webpack-contrib/worker-loader#226]
In order to support any kinds of existing workers such as WebWorker, ServiceWorker, SharedWorker and so on. Have you thought about return path which works like file-loader or url-loader? And then let the developers to decide which type of worker should use. It indirectly solve the service worker scenario under worker-loader

**Comment by developit** [comment]
Not sure if it'll get merged, but I PR'd support for this [back in 2018](https://github.com/webpack-contrib/worker-loader/pull/159).

FWIW you can use worker-plugin to achieve the desired result:

```js
import workerUrl from 'worker-plugin/lib/loader!./my-worker';
new Worker(workerUrl);
```

**Comment by evilebottnawi** [comment]
You don't need worker URL, this loader creates `Worker` by itself, `Worker` and `ServiceWorker` and `SharedWorker` already support in the master, ETA is near future
