### ISSUE TITLE
build hang with "Callback was already called"

### ISSUE THREAD

**Issue by light0x00** [webpack-contrib/worker-loader#229]
- node: v12.13.1
- "webpack": "^4.41.5"
- "worker-loader": "^2.0.0"

webpack.config

```
{
	test: /\.worker\.js$/,
	use: [{loader: "worker-loader",	options: { inline: true, fallback: false }} ]
},
```

worker

```
import marked from "./marked";
self.addEventListener("message", function (e) {
	self.postMessage(marked(e.data));
}, false);
```

caller

```
import Worker from "./marked.worker";
```

Whenever it is built, as long as the worker-loader is used, it will hang, but if the caller is removed, everything becomes normal

```
yarn run v1.19.2
$ node -r esm node_modules/.bin/webpack --config webpack.config.dev.js --progress
27% building 147/152 modules 5 active /Users/light/Desktop/my-workbench/_projects/parser-generator/node_modules/async-validator/es/rule/index.jsError: Callback was already called.
    at throwError (/Users/light/Desktop/my-workbench/_projects/parser-generator/node_modules/neo-async/async.js:16:11)
    at /Users/light/Desktop/my-workbench/_projects/parser-generator/node_modules/neo-async/async.js:2818:7
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

**Comment by ArvinTung** [comment]
@light0x00 how did you solve this ? I meet the same problem in web worker too, both in worker-loader and workerize-loader

**Comment by cmaster11** [comment]
@light0x00 I'm finding the same issue :O What did you do to solve it??

![wisdom_of_the_ancients](https://user-images.githubusercontent.com/3482407/114269631-da722500-9a10-11eb-8f7a-f5a1a88319c3.png)

**Comment by alexander-akait** [comment]
@cmaster11 Can you create reproducible test repo?

**Comment by cmaster11** [comment]
@alexander-akait sadly not, the project is quite big, and as soon as worker loader is added, the error happens. But if I find any fix, I'll let you know.

**Comment by alexander-akait** [comment]
@cmaster11 What is webpack version?

**Comment by cmaster11** [comment]
@alexander-akait `4.41.6`

**Comment by alexander-akait** [comment]
@cmaster11 maybe you apply worker-loader twicy, anyway I recommend to update webpack to v5 and remove this loader, because now we support it out of box

**Comment by cmaster11** [comment]
@alexander-akait thanks, will try :)
