### ISSUE TITLE
Error in Safari Mac OS

### ISSUE THREAD

**Issue by mrasoahaingo** [webpack-contrib/worker-loader#23]
Hello,

I got an error on the worker chunk file:

```
        // Convenience aliases.
        var objectProto = Object.prototype
```

```
dc85ec888f7b03108b40.worker.js:12880TypeError: undefined is not an object (evaluating 'Object.prototype')
```

It works fine on Chrome and Firefox. These are the versions I use:
Node 5.6.0
Npm 3.8.8
Babel 6

"webpack": "^1.12.9"
"worker-loader": "^0.7.0"

In my code:

```
import WebWorker from 'worker!client/workers/webWorker'
const webWorker = new WebWorker()
```

Thank you for your help

**Comment by michael-ciniawsky** [comment]
@mrasoahaingo You still have this regression with `v0.8.0` of the loader ? Which Safari version ?
