### ISSUE TITLE
Worker [hash] is not unique to each build in release mode

### ISSUE THREAD

**Issue by J-Rojas** [webpack-contrib/worker-loader#230]
I'm using worker-loader version 2.0.0. I'm encountering caching issues when building in release mode.

The main webpack release process produces chunks with unique hashes per build, however contrarily this module produces the same hash each time the release build is run. The generated hash appears to be based on the file contents only, not the content + the current build iteration.

**Comment by evilebottnawi** [comment]
@J-Rojas Sorry for delay, problem still exists? Can you create reproducible test repo?

**Comment by J-Rojas** [comment]
Going to close this for now as I have not encountered it recently. If it popup again I will reopen.
