### ISSUE TITLE
Options Documentation in README

### ISSUE THREAD

**Issue by sgpinkus** [webpack-contrib/worker-loader#239]
For options README gives this example:

```
// webpack.config.js
{
  loader: 'worker-loader',
  options: { fallback: false }
}
```

But that doesn't look like a `webpack.config.js`. Can you please give us more of a hint as to where this goes in the webpack config file?

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack-contrib/worker-loader/issues/253
