### ISSUE TITLE
Async call inside Worker's onmessage method

### ISSUE THREAD

**Issue by self-coding-crab** [webpack-contrib/worker-loader#240]
Hi Gents.

https://github.com/poma/websnark/blob/master/src/groth16.js#L98
Please check this code before my explanation.
As you can see from the code line, the async function is used inside the onmessage method.
I am using websnark as npm package like this:
`    "websnark": "git+https://github.com/peppersec/websnark.git#c254b5962287b788081be1047fa0041c2885b39f",
`

After research, I could use a worker-loader for the issue.
I am using react-app-rewired and here's my config-overrides.js file.
`const { override, fixBabelImports, addLessLoader, useBabelRc, addWebpackModuleRule } = require("customize-cra");
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const { IgnorePlugin } = require("webpack")

const ignorePlugin = new IgnorePlugin(/worker_threads/);
const miniCssExtractPlugin = new MiniCssExtractPlugin()
function myOverrides(config, env) {
  config.plugins.push(ignorePlugin);
  config.plugins.push(miniCssExtractPlugin)
  config.optimization.splitChunks = {
    cacheGroups: {
      default: false,
    },
  };
  // Move runtime into bundle instead of separate file
  config.optimization.runtimeChunk = false;
  config.optimization.minimize = false;
  config.optimization.minimizer = [];
  config.optimization.namedModules = false;
  config.optimization.moduleIds = 'named'
  // JS
  config.mode = 'development'
  
  return config
}

module.exports = override(
  fixBabelImports("import", {
    libraryName: "antd",
    libraryDirectory: "es",
    style: true
  }),
  useBabelRc(),
  addWebpackModuleRule(
    {
      test: /\.groth16\.js$/,
      include: /node_modules/,
      use: { loader: 'worker-loader' },
    }
  ),
  (config, env) => myOverrides(config, env)
);
`

As you can see from my config-overrides.js, I tried to integrate worker-loader but it still doesn't work.

Thanks

**Comment by evilebottnawi** [comment]
Please open an issue in `websnark`, not related to us

**Comment by self-coding-crab** [comment]
I don't think so. Not only the websnark but it will occur on the other packages using async method inside onmessage.

**Comment by evilebottnawi** [comment]
I can't understand, please create reproducible test repo
