### ISSUE TITLE
Safari/iOS not interpreting inline-webworkers correctly.

### ISSUE THREAD

**Issue by adamellsworth** [webpack-contrib/worker-loader#249]
- Operating System: macOS 10.14.6 (18G103)
- Node Version: 10.15.1+
- NPM Version: 6.14.5
- webpack Version: 4.43.0
- worker-loader Version: 2.0.0

### Expected Behavior

For `inline: true` to load static Webworker from source URI `https://our.url.com/[id].worker.js` instead of `blob://embed.url.com/[id].worker.js`. 

### Actual Behavior

We're seeing something in both Prod/Dev with how the `inline` functionality behaves:

![Screen Shot 2020-07-01 at 6 23 43 PM](https://user-images.githubusercontent.com/7034617/86308087-2e6ff380-bbcd-11ea-83b5-c5dd68ee1bdb.png)

The case here being that embedded instances of our app dont go back "home" as it were, but instead look at the parent pages URL and, not finding our webworker (on a different domain) it just ends up erring out.

### Code

__Webpack config:__
```js
output: {
    pathinfo: false,
    filename: 'app.js',
    path: __dirname + '/public',
    chunkFilename: '[id].worker.js'
},
rules: [
    {
        test: /\.worker\.js$/,
        use: [{
            loader: 'worker-loader',
            options: {
                inline: true,
                publicPath: '//our.url.com',
                fallback: false
            }
        }]
    }
]
```

__Imports:__ (a timer)
```js
import SessionWatcherWorker from './session-manager.worker.js'
const worker = new SessionWatcherWorker()
```

### How Do We Reproduce?

Use config above and embed on a site that is not the origin of the script on iOS/Safari (e.g. use a node server which points to an index.html which uses a script/iframe embed of another local site which actually compiles the webpack/worker-loader)

I'll put together one momentarily and add a new comment on this thread with the project ...

**Comment by evilebottnawi** [comment]
Do you read https://github.com/webpack-contrib/worker-loader#cross-origin-policy and https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src ? Can't reproduce locally

**Comment by evilebottnawi** [comment]
You have invalid url, I will look

**Comment by adamellsworth** [comment]
Sorry I fell asleep before I could get a demo project together. I'll put one together within 24hrs.

When you say i have an invalid URL do you mean this protocolless format is invalid: `publicPath: '//our.url.com',`? does it need to be `https://our.url.com`?

**Comment by evilebottnawi** [comment]
`publicPath` and `inline` should, not work together, no sense to use `publucPath` when you inline

**Comment by evilebottnawi** [comment]
Duplicate https://github.com/webpack-contrib/worker-loader/issues/211
