### ISSUE TITLE
Can't use workerType. options['workerType'] is an invalid additional property

### ISSUE THREAD

**Issue by Xdwlf** [webpack-contrib/worker-loader#250]
- Operating System: mac 10.14.6
- Node Version: 10.16.0
- NPM Version: 6.9.0
- webpack Version: ^4.42.1
- worker-loader Version: ^2.0.0

### Expected Behavior

For `workerType: "ServiceWorker"` to allow me to create a service-worker

### Actual Behavior

Webpack throws an error and the code for workerType is not included in the installed module.

```
ERROR in ./src/services/Worker/sw.ts
Module build failed (from ./node_modules/worker-loader/dist/cjs.js):
ValidationError: Worker Loader Invalid Options

options['workerType'] is an invalid additional property
at validateOptions (/Users/rlin/Desktop/review-wizard/node_modules/worker-loader/node_modules/schema-utils/src/validateOptions.js:31:11)
    at Object.pitch (/Users/rlin/Desktop/review-wizard/node_modules/worker-loader/dist/index.js:57:29)
 @ ./src/services/Worker/index.ts 6:0-33 10:46-59
 @ ./src/index.tsx
```

### Code

```js
            {
                test: /sw\.ts$/,
                loader: 'worker-loader',
                options: {
                    workerType: 'ServiceWorker'
                },
            },

```

### How Do We Reproduce?

Use npm install --save-dev worker-loader and use the workerType option.

**Comment by evilebottnawi** [comment]
It is not released yet

**Comment by Xdwlf** [comment]
Awesome. Thanks you for the update!

**Comment by planty** [comment]
Has this been released yet? Really interested in trying it out!

**Comment by evilebottnawi** [comment]
Release is the next of current week, yes it will support SharedWorker

**Comment by planty** [comment]
Great news, thank you.

**Comment by kosk** [comment]
@evilebottnawi, do you have a release date for this feature?

**Comment by evilebottnawi** [comment]
@kosk Small delay, ETA is this week
