### ISSUE TITLE
After updating to 3.0.7: ERROR in The comment file conflicts with an existing asset, this may lead to code corruption, please use a different name

### ISSUE THREAD

**Issue by jens-duttke** [webpack-contrib/worker-loader#260]
After updating from 3.0.6 to 3.0.7 I get the following errors in the build process:
> ERROR in The comment file "js/Search.worker.EgOGw6YJ.js.LICENSE.txt" conflicts with an existing asset, this may lead to code corruption, please use a different name
> ERROR in The comment file "js/TypeDetection.worker.CsfjJfHv.js.LICENSE.txt" conflicts with an existing asset, this may lead to code corruption, please use a different name 

After downgrading to 3.0.6 without to change anything else, everything works fine, so the problem is something which has been changed in 3.0.7.

The mentioned files are the only two workers which I'm using in the project, all other files don't seems to have this problem.
For compile the workers code, I'm using the worker-loader

- Operating System: Windows 10 Pro
- Node Version: 14.4.0
- NPM Version: 6.14.5
- webpack Version: 4.43.0
- terser-webpack-plugin Version: 3.0.7
- worker-loader Version: 2.0.0

### Expected Behavior

Compilation without errors.

### Actual Behavior

Errors in the compilation process.

### Code

```js
...
		optimization: {
			minimizer: [
				new TerserPlugin({
					terserOptions: {
						output: {
							max_line_len: 10
						}
					}
				}),
				new OptimizeCSSAssetsPlugin({})
			],
...
				{
					test: /\.worker\.ts$/u,
					use: [
						{
							loader: 'worker-loader',
							options: {
								name: 'js/[name].[hash].js',
								publicPath: '/' // CDN path here
							}
						},
						{
							loader: 'babel-loader'
						}
					]
				},
...
```

**Comment by evilebottnawi** [comment]
Workaround downgrade to `3.0.6` or disable extract comments

**Comment by evilebottnawi** [comment]
Fixed https://github.com/webpack-contrib/terser-webpack-plugin/pull/279, It was easy to fix on `terser-webpack-side`
