### ISSUE TITLE
After updating to 3.0.0 the base file names are not based on the source file name anymore

### ISSUE THREAD

**Issue by jens-duttke** [webpack-contrib/worker-loader#276]
Now, after the update to version 3.0.0 (and replacing `name` by `filename`), it uses the name of the "main"-chunk, instead of the name of by worker files:

`Search.worker.ts` results into `main.CuC84dZH.js`, `main.CuC84dZH.js.map` and `main.CuC84dZH.js.LICENSE.txt`.

`TypeDetection.worker.ts` results into `main.CsGA6GIM.js`, `main.CsGA6GIM.js.map` and `main.CsGA6GIM.js.LICENSE.txt`

Beside that, I have the `main.HeMLeGN2.min.js` and `main.HeMLeGN2.min.js.map` containing the main chunk.

I've also tried to switch to `chunkFilename` or use `[id].worker.js`, but this doesn't help.

Any idea how to get the old behaviour?

- Operating System: Windows 10 Pro
- Node Version: 14.4.0
- NPM Version: 6.14.5
- webpack Version: 4.44.1
- worker-loader Version: 3.0.0

### Expected Behavior

The output files should have the same base file name as the source files.

### Actual Behavior

The output files get the name of the "main" chunk.

### Code

```js
{
	test: /\.worker\.ts$/u,
	use: [
		{
			loader: 'worker-loader',
			options: {
				name: 'js/[name].[hash].js',
				publicPath: '/' // CDN path here
			}
		},
		{
			loader: 'babel-loader'
		}
	]
},
``````

I'm importing the Worker on this way:
```js
import Worker, { EventData, TypeInformation } from './TypeDetection.worker';
```

**Comment by evilebottnawi** [comment]
Hm, yes, you are right, it is bug, non critical (becase you have `worker` suffix), but will be great to fix it
