### ISSUE TITLE
Syntax error: unexpected token: ':' when setting option inline to no-fallback

### ISSUE THREAD

**Issue by schl3ck** [webpack-contrib/worker-loader#285]
Hi!
This issue was already reported at webpack https://github.com/webpack/webpack/issues/11417 but it looks more like an issue with this loader.

- Operating System: Windows 10 Pro, Version 2004
- Node Version: 14.5.0
- NPM Version: 6.14.5
- webpack Version: 4.44.1
- worker-loader Version: 3.0.2

### Expected Behavior
To run the worker file without problems.

### Actual Behavior
I get `Syntax error: unexpected token: ':'` and the worker isn't executed.
The syntax error happens at the end of the file where the source map comments are inserted. Somehow the last line has no `//` prefixed.

### Code
Standard vue.js config with the rule added:

```js
{
  test: /\.worker\.js$/i,
  use: [
    /* config.module.rule('worker').use('worker-loader') */
    {
      loader: 'worker-loader',
      options: {
        inline: 'no-fallback'
      }
    }
  ]
}
```

### How Do We Reproduce?
I created a new vue.js project with @vue/cli using vue.js 2 and babel, everything else was deselected. With the worker-loader added and a simple worker script invoked from src/App.vue:

https://github.com/schl3ck/worker-loader-inline-no-fallback

**Comment by evilebottnawi** [comment]
Feel free to send PR with fix

**Comment by wavebeem** [comment]
I wanted to add from my issue that this only happens with certain `devtool` options:

- eval-source-map
- eval-cheap-source-map
- eval-nosources-source-map
- eval-cheap-module-source-map
- eval-nosources-cheap-source-map
- eval-nosources-cheap-module-source-map

**Comment by schl3ck** [comment]
I don't know how vue does it, but upon running `vue inspect` I don't see a devtool option being set. Maybe it is set indirectly through another option.

**Comment by schl3ck** [comment]
So I dug in and found the cause. My repro doesn't reproduce it because I've forgotten to also use `babel-loader`.

That aside, the bug is in the regex:
https://github.com/webpack-contrib/worker-loader/blob/17f81c121e53a45afef52bf05f97c2bbea536c61/src/utils.js#L90
Specifically the part `([^\s'"]*)`. This matches until a whitespace character or quote is found. The thing is that the script is embedded so the new line character is escaped as `\n` and therefore not matched by the regex.

If someone needs an illustration: https://regex101.com/r/c7sthM/1
Open up the regex debugger, set end to 15902 and beginning to 15880, now scroll through until the whole base64 block is matched.

I will try and fix this (shouldn't be that hard)!
