### ISSUE TITLE
worker-loader does not work with "worker_threads"

### ISSUE THREAD

**Issue by EgorCloud** [webpack-contrib/worker-loader#288]
- Operating System: Windows 10
- Node Version: 12.16.1
- NPM Version: 6.14.7
- webpack Version: 4.44.2
- worker-loader Version: 3.0.2

### Expected Behavior
normal wrapping of worker name with require.resolve ()

### Actual Behavior
When I use worker-loader with worker_threads
Webpack misbehaves with require.resolve
[image](https://prnt.sc/ukqpgq)
[error](https://prnt.sc/ukqqt4)
I cannot further describe the problem, because I have no idea what it is.

### Code
[webpack.config.js](https://gist.github.com/EgorCloud/24049b09bc50ef7b32cb850a96d12004)

index.js
```js
import { Worker } from 'worker_threads';

for (let index = 0; index < 999; index++) {
    let wp = new Worker(require.resolve('./workers/index.worker.js'));
    wp.on('message', (message) => {
        console.log(message)
    });
}
```

```js
let { parentPort } = require('worker_threads')
parentPort.postMessage("Worker!")

```

### How Do We Reproduce?
1. paste files to test project
2. 
```shell script
$ webpack
```
3.
```shell script
$ node build/main.js
```

**Comment by evilebottnawi** [comment]
`worker-loader` doesn't work with `Node.js` workers, and never work, it is for browser

**Comment by EgorCloud** [comment]
> 
> 
> `worker-loader` doesn't work with `Node.js` workers, and never work, it is for browser

so, can you tell me which plugin or loader will help?

**Comment by evilebottnawi** [comment]
@EgorCloud webpack@5 will help, workers supported out of box
