### ISSUE TITLE
docs don't explain how to register ServiceWorker

### ISSUE THREAD

**Issue by akosyakov** [webpack-contrib/worker-loader#297]
Documentation Is:

- [x] Missing
- [ ] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

One has to call `navigator.serviceWorker.register` at some point with the specific script URL. Is it done by this loader automatically? What import actually does? Clarification would be helpful.

**Comment by evilebottnawi** [comment]
Sorry it is out of scope loader, please use mdn we just return web worker
