### ISSUE TITLE
Inline workers not working _in_ a worker

### ISSUE THREAD

**Issue by MatthewSteel** [webpack-contrib/worker-loader#306]
### Expected Behavior / Situation

I have a library that creates an "inline" worker. Normally the library is used from the `Window` (main browser thread) scope, and things work fine, but now I want to use it from a worker scope. I'd expect the worker that uses the library to create a second "child" inline worker.

### Actual Behavior / Situation

An error gets thrown, no child worker gets created. The error is caused by references to `window` in [this file](https://github.com/webpack-contrib/worker-loader/blob/08fa5c5c9984b9dda46c422d65ef83c92f2ef368/src/runtime/inline.js#L11).

### Modification Proposal

Replace uses of `window` in src/runtime/inline.js with `self`. I've checked that this fixes behaviour for me, but don't know what'd else you might need in terms of testing/validation. Happy to make a PR myself if it would help get this done and released more quickly, but it could slow things down if there are hoops to jump through that I'm not familiar with.

**Comment by alexander-akait** [comment]
What is webpack version?

**Comment by MatthewSteel** [comment]
The library that creates an inline-worker was built with webpack version 4.41.2 when I saw the issue.

Could building it with a different version help? (Fixing my issue by upgrading deps, or by providing some build-time configuration to make those `window` references resolve to something else would definitely be fine for me.)

**Comment by alexander-akait** [comment]
> Could building it with a different version help? (Fixing my issue by upgrading deps, or by providing some build-time configuration to make those window references resolve to something else would definitely be fine for me.)

Do you use `webpack`? Or you try to import library that will be bundled by webpack?

**Comment by MatthewSteel** [comment]
My application imports the library bundled by webpack from inside a worker. The library is built by running `webpack`. The library uses `worker-loader`, and it creates inline workers.

I can change either or both of them. I would like to continue using inline workers inside the library if possible.

**Comment by alexander-akait** [comment]
Yep, let's fix it, just notice - webpack v5 does not require worker-loader

**Comment by MatthewSteel** [comment]
Ah, maybe I should try to build my library with webpack 5, but I think it'd be a bigger job :-).

Should I make a find/replace PR, or would you prefer to fix and release?

**Comment by alexander-akait** [comment]
Feel free to send a fix and I will publish patch release

**Comment by alexander-akait** [comment]
Just do `(self || window)`

**Comment by MatthewSteel** [comment]
Oof, I'm not great at using github -- I ran into a push permission error. I put a patch in a [gist](https://gist.github.com/MatthewSteel/0987d1fa11d0cec3360c53847d916d54) you can apply with `git am <patch-file>` if it helps.

**Comment by alexander-akait** [comment]
@MatthewSteel You need fork this repo send a PR to fork, when return to this repo and go to `PR` and send a PR

**Comment by MatthewSteel** [comment]
(Let me know if I've done this wrong. Can make whatever changes needed. Looks like code coverage checks are failing, which I guess could be fixed by inlining the expression everywhere? Dunno.)

**Comment by MatthewSteel** [comment]
Thanks for shepherding this through!

**Comment by MatthewSteel** [comment]
Oh, one more question: This change fixed our issue at an older version, but we have a separate but related issue while upgrading to the latest version: I think [the changed externals behaviour](https://github.com/webpack-contrib/worker-loader/pull/264/files) might have caused problems for inline workers. I _think_ the blob URLs need to include all of their transitive dependencies.

I'm not 100% sure that's the right diagnosis, and I'm even less sure what the right remedy would be. In the meantime I think the simplest thing for my team to do is to apply the patch from this issue to a private fork before the externals change.

**Comment by alexander-akait** [comment]
Can you clarify?

**Comment by MatthewSteel** [comment]
My library uses the "externals" webpack configuration so its package deps aren't included in the built bundle -- they're provided by my application.

For non-inline workers, I guess the application's webpack process "links" the generated .worker.js files to their dependencies, but for inline workers I think the linking process doesn't work -- the application's webpack doesn't know how to include the dependencies in the string/blob worker source.

One workaround on my side could be to not mark these deps as externals. But I think a better solution is to ignore "externals" for inline workers.

**Comment by alexander-akait** [comment]
Hard to understand, maybe you can provide simple reproducible test repo, so I will undestand what do you want achieve
