### ISSUE TITLE
loader.option.publicPath do not work ?

### ISSUE THREAD

**Issue by huyansheng3** [webpack-contrib/worker-loader#323]
- Operating System:
- Node Version:
- NPM Version:
- webpack Version:
- worker-loader Version:latest

when i run the test case, *.chunk.js use the loader.option.publicPath, but the *.worker.js do not use  the loader.option.publicPath

```
it('should work and respect the "output.publicPath" option default value', async () => {
    const nanoid = customAlphabet("1234567890abcdef", 10);
    const compiler = getCompiler(
      "./chunks/entry.js",
      {
        worker: "SharedWorker",
        filename: "[name].[contenthash].worker.js",
        chunkFilename: "[id].[contenthash].worker.js",
        publicPath: "/public-path-static123/",
      },
      {
        output: {
          path: path.resolve(__dirname, "./outputs", `test_${nanoid()}`),
          filename: "[name].bundle.js",
          chunkFilename: "[name].chunk.js",
          publicPath: "/public-path-static456/",
        },
      }
    );
    const stats = await compile(compiler);
    const result = await getResultFromBrowser(stats);

    expect(getModuleSource("./chunks/worker.js", stats)).toMatchSnapshot(
      "module"
    );
    expect(result).toMatchSnapshot("result");
    expect(getWarnings(stats)).toMatchSnapshot("warnings");
    expect(getErrors(stats)).toMatchSnapshot("errors");
  });

```

![image](https://user-images.githubusercontent.com/11534583/123795338-7fb4df00-d916-11eb-8b76-00f4e7e6d982.png)

![image](https://user-images.githubusercontent.com/11534583/123795381-8ba0a100-d916-11eb-9adc-803f984df1a8.png)

`http://localhost:5000/public-path-static456/worker.9ce1180cb43e7000b1a2.worker.js` should be `/public-path-static123/worker.9ce1180cb43e7000b1a2.worker.js` ?

**Comment by alexander-akait** [comment]
What is webpack version?

**Comment by huyansheng3** [comment]
wepack 4.x or 5.x has the same problem .

I just  modify the project test case; then see the outputs content

**Comment by alexander-akait** [comment]
you don't need this loader for webpack v5

**Comment by huyansheng3** [comment]
oader.option.publicPath only add to the webpack output.publicPath, can only set the worker.js full public path

**Comment by mmazzarolo** [comment]
@alexander-akait just a note: AFAIK Webpack 5 implementation of the loading mechanism doesn't support setting `publicPath` specific only to web-workers. It will always use whatever is set in `output.publicPath` (which might not be the same path you need for the worker).
