### ISSUE TITLE
How to use with babel-loader ?

### ISSUE THREAD

**Issue by kevzettler** [webpack-contrib/worker-loader#35]
I'm trying to use `worker-loader` with `babel` for es6 import support in web worker code. The readme says this is possible but I guess I need a better example.

I have the following setup in my `webpack.config.js`

```
   {
     test: /\.worker\.js$/,
     loader: "worker!babel",
     presets: ['es2015']
   }
```

This correctly produces a sepearte bundle file for the worker with a hash name like `d46f60b8e184bf8b1cb8.worker.js`

However this file is not run through the Babel transforms and converted to es5. So it contains raw es6 import statmenets and syntax that is failing in a browser. Looks like:

```
/* 0 */
/***/ function(module, exports) {

    import _ from 'lodash';

    var o = {foo: 'foo'};

    _.has(o, 'foo'); // true

    setInterval(() => {
       postMessage({tick: Date.now()});
    }, 1000);


/***/ }
/******/ ]);
```

I have tried switching the order of the loaders like:

```
   {
     test: /\.worker\.js$/,
     loader: "babel!worker",
     presets: ['es2015']
   }
```

and also tried moving it to `preLoaders` and `postLoaders` with no success.

**Comment by kevzettler** [comment]
sorry my babel setup was messed up

**Comment by SpaceK33z** [comment]
Have you tried creating a `.babelrc` file next to your `webpack.config.js` file with the contents:

```
{
  presets: ["es2015"]
}
```

The `presets` option is not valid where you use it.

**Comment by steffanhalv** [comment]
@kevzettler Did you ever get this working with babel?

**Comment by patoncrispy** [comment]
I am stuck on this too. Does anybody have a valid solution?

**Comment by patoncrispy** [comment]
Got mine working. My rule is:

```
      {
        test: /worker\.js$/,
        include: paths.appSrc,
        use: [
          { loader: 'worker-loader' },
          { loader: 'babel-loader' }
        ]
      },
```

my .babelrc

```
{
  "presets": ["es2015", "stage-0"]
}
```

I also have `import 'babel-polyfill'` at the start of my web worker. As you can see from my loader, all workers must have the suffix `worker.js`.

**Comment by TrySound** [comment]
@patoncrispy Thanks!

**Comment by kevzettler** [comment]
Would be a good idea to add this to the documentation

**Comment by TrySound** [comment]
@kevzettler I guess it can be in webpack documentation. It's just about using loaders in one pipeline, not special case for worker-loader

**Comment by heyitsjames** [comment]
For anyone on a non-ejected instance of `create-react-app` (which means you can't edit the webpack config), I got this working like this:

`npm install worker-loader`
`npm install babel-polyfill`

in worker.js:

```
import 'babel-polyfill`
.
. // worker code here
.
```

in the file that is importing `worker.js`:

`const Worker = require("worker-loader!./worker.js");`
`const myWorker = new Worker()`

Works great in IE11, which is the one that was causing me problems. Hope that helps!

**Comment by iandoe** [comment]
Just an update in 2019 / 2020 with `Babel 7+` this is how i got mine working:

in `webpack.config.js`: 
```
{
  test: /\.worker\.js$/,
  loaders: ['worker-loader', 'babel-loader'],
}
```

at the top of `MyWorker.worker.js` file: 

```
import 'core-js/stable'
import 'regenerator-runtime/runtime'
```

In case that can help anyone trying to get this to work in Edge / IE11

Cheers
