### ISSUE TITLE
Define output worker file path and name

### ISSUE THREAD

**Issue by brucejcw** [webpack-contrib/worker-loader#36]
how to define? [example](https://github.com/webpack/webpack/blob/master/examples/web-worker/webpack.config.js) doesn't work

**Comment by zhanghaowx** [comment]
I am also very curious to learn how to do it correctly

**Comment by mariotacke** [comment]
Did you ever figure out how to do this with webpack 1 without the inline option?

**Comment by zhanghaowx** [comment]
@mariotacke 

        worker: {
            output: {
                filename: "developer/dist/[hash].worker.js",
            }
        }
should do the trick to put your worker file into the folder you want. However, you cannot use 

    [name].worker.js
if you have more than one worker file. But you can watch https://github.com/webpack-contrib/worker-loader/pull/22 and hopefully it will get merged soon.

**Comment by drcmda** [comment]
Couldn't it simply use the chunks pattern? Most configs already have:

    chunkFilename: 'build/chunk.[id].js',

The problem is that we distribute our lib, and this forces customers to add this stuff to their configs or otherwise the worker is dumped into the root folder with a random hashname.

**Comment by TrySound** [comment]
Name option should work now
