### ISSUE TITLE
webpack externals config is ignored

### ISSUE THREAD

**Issue by ducret201** [webpack-contrib/worker-loader#37]
In the worker dependencies, modules defined as [externals](https://webpack.github.io/docs/library-and-externals.html) are not found.

**Comment by PendletonJones** [comment]
this is highly problematic for me. would love to hear more on this issue, in the mean time I will do more searching

**Comment by TrySound** [comment]
@ducret201 @PendletonJones Guys, how do you cosider to use externals with isolated worker environment?

**Comment by vamcc** [comment]
I have lodash as one of my externals and want to use it in the isolated worker. Hope that [pr #42](https://github.com/webpack-contrib/worker-loader/pull/42) can be merged ASAP.

**Comment by TrySound** [comment]
@vamcc You mean lodash is a global variable?

**Comment by vamcc** [comment]
@TrySound Yes, lodash is a global variable in my project.

**Comment by TrySound** [comment]
@vamcc As you said worker is isolated. This means you can't access to `window` from workers. So you can't use externals.

**Comment by vamcc** [comment]
@TrySound So, will it work if externals are in a UMD mode?

**Comment by TrySound** [comment]
Nope. Dependencies should be bundled with worker and be loaded via `importScript`.

**Comment by vamcc** [comment]
@TrySound Worker-loader won't support externals?

**Comment by TrySound** [comment]
@vamcc WebWorkers won't support window global variables. Parallel processes can't share non-functional code. Processes should be independent.

**Comment by vamcc** [comment]
@TrySound Ok, thank you.
