### ISSUE TITLE
importScripts() only works when imported script is in root

### ISSUE THREAD

**Issue by nakedsushi** [webpack-contrib/worker-loader#39]
My angular2 app uses web workers and uses webpack for bundling.

My worker and its supporting scripts are in one directory (upload/).  The script that does the `require('worker!...')` is one directory up from (upload/).  In my worker script, I have an `importScripts('encoder.js')`, which I believe is the correct path since the worker and encoder.js are both in the same (upload/) directory.

My app keeps looking for `encoder.js` in the root directory and not in the upload/ directory.  How do I make it so that webpack informs `importScripts()` of where encoder.js is?

**Comment by m-andrew-albright** [comment]
@nakedsushi 

Did you ever figure out how to handle `importScripts()` for scripts not located at root?  I specifically have an npm package (xlsx.js) which includes a web worker for doing the heavy lifting, but the web worker script is using `importScripts()` to reference some of the package's dependencies that are included in the npm package, in the same `node_modules/xlsx` directory.

I was able to get it working just by manually copying the dependencies into my root directory, but this is obviously not idea.

**Comment by m-andrew-albright** [comment]
@nakedsushi in your web worker, you need to change your `importScripts('dependency')` to `require('dependency')`.  Webpack seems to be able to resolve my dependencies when I did this.

**Comment by nakedsushi** [comment]
@m-andrew-albright I ended up pointing to the relative path of my script, but your method works as well thanks!
