### ISSUE TITLE
[Bug] `importScripts` inside web worker loses context

### ISSUE THREAD

**Issue by rahulgandhi** [webpack-contrib/worker-loader#45]
I'm facing a bug here. 
I'm using worker-loader to load webworkers in my project. My web worker script uses importScripts to download other scripts and execute them. According to [](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) 

> The browser loads each listed script and executes it. Any global objects from each script may then be used by the worker.

However, this is not what happens when I use worker-loader. 

This is what happens.

```
var Worker = require("worker-loader!./myWorker.js");
var worker = new Worker;

// myWorker.js
var x = x || {};
importScripts("a.js");
x.name // "undefined"


//a.js
var x = x || {};
x.name = "hello";
```

This is what happens (expected) when I don't use a worker-loader

```
var worker = window.Worker("myWorker.js");

// myWorker.js
var x = x || {};
importScripts("a.js");
x.name // "hello"


//a.js
var x = x || {};
x.name = "hello";
```

I've created a test repo in case you want to reproduce it.
[worker-loader](https://github.com/rahulgandhi/webpack_webworker)

webpack version: 2.2.1
worker-loader version 0.7.1
node version 6.9.5

**Comment by Dinfyru** [comment]
+1

**Comment by agirault** [comment]
+1

**Comment by caitlin615** [comment]
Still an issue. Any ideas on a fix?

**Comment by kevrat** [comment]
+1

**Comment by evilebottnawi** [comment]
PR welcome :+1:

**Comment by rahulgandhi** [comment]
@evilebottnawi I can pick it up if someone can give me some pointers.

**Comment by evilebottnawi** [comment]
Original issue ref https://github.com/webpack/webpack/issues/4234

**Comment by yangsibai** [comment]
Replace `importScripts("a.js");` with `require("a.js")`.

**Comment by mo-xiaoming** [comment]
Problem remains on worker-loader 2.0.0

**Comment by evilebottnawi** [comment]
It is the limitation, webpack wrap module code, like:
```js
(function(module, exports) {
  var x = x || {};
  importScripts("a.js");
  console.log(x.name);
})();
```

It helps to not expose local variables to global object (windows, self, etc). You can solve this problems using:
```js
var Worker = require("worker-loader!./myWorker.js");
var worker = new Worker;

// myWorker.js
self.x = self.x || {};
importScripts("a.js");
self.x.name // "undefined"


//a.js
self.x = self.x || {};
self.x.name = "hello";
```

For webpack@5, we respect the `output.iife` option, so you need to set `iife: false` and all works fine. But I recommend that you do not use this approach, because it is potentially unsafe.
