### ISSUE TITLE
Multiple entries / output

### ISSUE THREAD

**Issue by ea167** [webpack-contrib/worker-loader#54]
Hi,

Looking at the code, it looks like the loader does not manage the "entry:" directive inside the "worker:" directive of webpack.config.js, and that it takes by default entries[0] in runAsChild()

Is there a way for the loader to manage several worker files?

Thank you for any help!

**Comment by TrySound** [comment]
@ea167 What do you mean "several"?
Every imported or required file with loader in pipe is processed correctly.
You may use this way
```
var MyWorker = require("worker-loader!./myWorker.js");
```
or customize config
```
{
  test: /\.ww\.js$/,
  loader: 'worker-loader'
}
```
