### ISSUE TITLE
Worker bundle contains first level deep dependencies

### ISSUE THREAD

**Issue by knee-cola** [webpack-contrib/worker-loader#56]
When the worker code imports modules (first level) which import other modules (second level), then modules from second level are not included in the output worker bundle file.

Here's an illustration:
Worker.js -> import moduleA -> import moduleB

The **moduleA** will be included in the worker.bundle.js, while **moduleB** will not be included.

Is this the expected behaviour or an I doing something wrong?

**Comment by TrySound** [comment]
@knee-cola I guess it's a bug. Would like to provide a test case?

**Comment by knee-cola** [comment]
While trying to reproduce the issue I discovered that it works as expected. I misdiagnosed the problem.
