### ISSUE TITLE
Standardize README

### ISSUE THREAD

**Issue by michael-ciniawsky** [webpack-contrib/worker-loader#62]

**Comment by TrySound** [comment]
@michael-ciniawsky Standard was changed again?:)

**Comment by michael-ciniawsky** [comment]
@TrySound Not really just 'improved/moved on' nothing fancy or urgent just nitpicks here, I do it when I have time 😛

**Comment by michael-ciniawsky** [comment]
It's mainly to be 'mostly accurate' since the README's are on the docs page :)
