### ISSUE TITLE
[Feature] support `ModuleWorkers`

### ISSUE THREAD

**Issue by TrySound** [webpack-contrib/worker-loader#67]
https://html.spec.whatwg.org/multipage/workers.html#module-worker-example

**Comment by Narvey** [comment]
Yuck, so the readme says to do this, but you actually can't yet?

**Comment by michael8090** [comment]
For now worker-loader doesn't support cross origin files, maybe we can support it by:
1. using `new Worker('https://some.other.origin', {type: 'module'})`, or
2. using JSONP

What do you guys think?

**Comment by raphaelbs** [comment]
Chrome 80 shipped with support for this: https://www.chromestatus.com/feature/5761300827209728

How about adding an option to enable it? Jason Miller made [this gist](https://gist.github.com/developit/5b09dc86c644d76f8fbd8abe294440f2) to check support for module workers.

**Comment by evilebottnawi** [comment]
Done https://github.com/webpack-contrib/worker-loader/pull/255, you can set worker options, docs will be updated in the near future
