### ISSUE TITLE
worker-loader makes it very hard to distribute code

### ISSUE THREAD

**Issue by drcmda** [webpack-contrib/worker-loader#71]
Our main gripe is that it still insists spitting out a separate file, even if the inline option is set to true. This forces _everyone using the component_ to change their webpack configs:

    plugins: [
        new webpack.LoaderOptionsPlugin({ 
            options: { 
                worker: { 
                    output: { filename: 'build/worker.js' } 
                } 
            } 
        }),

😨

... or else worker-loader will stack randomly hash-named files into the projects root dir, which is very impractical. All our customers have complained about this and we just don't know what to do. We could bundle all code and create a Blob by hand, but that would mix gulp stuff into webpack again.

I suggest that

1. inline finally respects the true setting without fallbacks

2. it fetches the chunkFilename to determine where to store the file and under which name

Best solution would be if a loader existed that could cook a readymade, require-resolved bundle so that we can use it together with raw-loader in order to create our own blobs.

**Comment by mariotacke** [comment]
I think #22 and #30 are trying to address it.

**Comment by TrySound** [comment]
@drcmda If you will look in documentation you will find not only inline option but also fallback which prevents creating that file.
```js
var MyWorker = require("worker-loader?inline&fallback=false!./myWorker.js");
```
