### ISSUE TITLE
0.8.1 causes build error with webpack 2. Downgrading to 0.8.0 solves it.

### ISSUE THREAD

**Issue by Keyamoon** [webpack-contrib/worker-loader#84]
Thought to let you know that I was getting this error with webpack v2.6.1 and worker-loader v0.8.1:

```
Module build failed: TypeError: loaderUtils.getOptions is not a function
    at Object.pitch (./node_modules/worker-loader/index.js:27:31)
```

Downgrading to 0.8.0 resolved the issue for me.

**Comment by d3viant0ne** [comment]
@Keyamoon - Not entirely sure where that version is coming from as there is not tag in github though it exists on npm.

To that specific error. See this comment & associated commit: https://github.com/webpack-contrib/worker-loader/commit/7806d503433bee676070630c939bc923d6358775#commitcomment-23238510

The loader-utils upgrade is breaking & requires a semver Major. I'll get it fixed but for the time being, you will need to pin to 0.8.0
