### ISSUE TITLE
[Question] Get blob URL instead of worker instance

### ISSUE THREAD

**Issue by gund** [webpack-contrib/worker-loader#88]
I want to use this loader in Angular project to bootstrap application via `@angular/webworker-platform`.

And that API requires to pass a URL string and then angular itself will bootstrap and instantiate the worker.

So my question is can I somehow get just a blob URL of the worker script and not an object to call `new` on it?

Thanks

**Comment by gund** [comment]
I found this feature [here](https://github.com/borisirota/webworkify-webpack) but I think we can still have it in this lib...

**Comment by michael-ciniawsky** [comment]
https://github.com/webpack-contrib/worker-loader#inline
